--[[
	Please use only quotation marks instead of apostrophs for JSON export.
	Do not change this modul without need. A change causes the parsing of the
	majority of articles. Wishes for new types should be discussed and collected
	on Module talk:Marker utilities/Types.
	Types should conform to tags in Openstreetmap, if possible.
	New types must be entered in Template:Marker/XML and Template:vCard/XML, too.
--]]

return {
	-- administration
	moduleInterface = {
		suite  = "Marker utilities",
		sub    = "types",
		serial = "2023-02-03",
		item   = 65444106
	},

	types = {
		-- journey and mobility

		aerialway = { group = "go", wd = { "Q1424016" }, label = "ケーブルカー" },
		airline = { group = "go", wd = { "Q46970" }, label = "航空会社" },
		airport = { group = "go", wd = { "Q1248784", "Q62447", "Q644371" }, useIATA = "1", label = "空港" },
		airport_service = { group = "go", label = "空港サービス" },
		bicycle_parking = { group = "go", wd = { "Q16243822" }, label = "駐輪場" },
		bicycle_rental = { alias = "bicycle_share", group = "go", wd = { "Q10611118", "Q1358919" }, label = "レンタサイクル", icon = "bicycle-share" },
		boat_sharing = { group = "go", wd = { "Q4931514" }, label = "ボートシェアリング" },
		boat_trip = { group = "go", wd = { "Q25040412" }, label = "船旅" },
		border_control = { group = "go", wd = { "Q218719" }, label = "出入国管理" },
		bus = { alias = "bus_stop", group = "go", wd = { "Q953806", "Q494829" }, label = "バス停" },
		car_rental = { group = "go", wd = { "Q291240" }, label = "レンタカー" },
		car_repair = { group = "go", wd = { "Q1310967" }, label = "自動車修理工場" },
		car_sharing = { group = "go", wd = { "Q847201" }, label = "カーシェアリング" },
		charging_station = { group = "go", wd = { "Q2140665", "Q55956304" }, label = "充電ステーション" },
		cycle_track = { group = "go", wd = { "Q25037910", "Q221722" }, label = "自転車道" },
		ferry = { group = "go", wd = { "Q100355757", "Q25653", "Q1478783" }, label = "フェリー乗り場" },
		fuel = { group = "go", wd = { "Q205495" }, label = "ガソリンスタンド" },
		funicular = { group = "go", wd = { "Q142031" }, label = "ケーブルカー" },
		harbor = { alias = "port", group = "go", wd = { "Q44782", "Q283202" }, label = "港" },
		heliport = { group = "go", wd = { "Q502074" }, label = "ヘリポート" },
        junction = { alias = { "road_junction", "intersection" }, group = "go", wd = { "Q1788454", "Q285783" }, label = "交差点、ジャンクション" },
		landing_site = { group = "go", wd = { "Q3631092" }, label = "離着陸場" },
		left_luggage = { group = "go", wd = { "Q21996814" }, label = "手荷物置き場" },
		light_railway = { group = "go", wd = { "Q32680449" }, label = "軽便鉄道" },
		marina = { group = "go", wd = { "Q721207" }, label = "ヨットハーバー" },
		monorail = { group = "go", wd = { "Q187934" }, label = "モノレール駅" },
		motorbike_rental = { group = "go", label = "バイク貸出所" },
		motorway_junction = { group = "go", label = "高速道路のジャンクション" },
		parking = { group = "go", wd = { "Q6501349" }, label = "駐車場" },
		parking_garage = { group = "go", wd = { "Q13218805" }, label = "車庫" },
		pier = { group = "go", wd = { "Q863454" }, label = "桟橋" }, -- also jetty
		public_transport = { group = "go", wd = { "Q178512" }, label = "公共交通機関" },
		quay = { alias = "wharf", group = "go", wd = { "Q828909" }, label = "埠頭" },
		rail = { alias = { "train", "railway", "railway_station" }, group = "go", wd = { "Q55488", "Q55678" }, label = "鉄道駅" },
		scooter = { group = "go", wd = { "Q193234", "Q502057" }, label = "スクーター" },
		service_area = { group = "go", wd = { "Q786014" }, label = "サービスエリア" },
		ship = { group = "go", wd = { "Q11446" }, label = "大型船舶" },
		shipping_company = { group = "go", label = "船会社" },
		shuttle_bus_service = { group = "go", label = "シャトルバス" },
		station = { group = "go", wd = { "Q12819564" }, label = "駅" },
		subway = { alias = "metro", group = "go", wd = { "Q928830" }, label = "地下鉄", icon = "rail-metro" },
		taxi = { group = "go", wd = { "Q1395196" }, label = "タクシー" },
		terminal = { group = "go", wd = { "Q849706" }, label = "ターミナル" },
		toll_station = { group = "go", wd = { "Q1364150" }, label = "料金所" },
		tram = { group = "go", wd = { "Q2175765" }, label = "路面電車停留所", icon = "rail-light" },
		tunnel = { group = "go", wd = { "Q44377" }, label = "トンネル" },
		waiting_room = { group = "go", wd = { "Q674251" }, label = "待合室" },
		waypoint = { group = "go", wd = { "Q138081" }, label = "ウェイポイント" },
		-- group types
		go = { group = "go", wd = { "Q334166", "Q740752" }, label = "交通手段" },

		-- sights: religious sites and monuments

		altar = { group = "religion", wd = { "Q101687" }, label = "祭壇" },
		bahai_temple = { group = "religion", wd = { "Q1568313" }, label = "マシュリク・ル・アヅカル" },
		basilica = { group = "religion", wd = { "Q163687", "Q4846867" }, label = "バシリカ" },
		buddharupa = { group = "religion", wd = { "Q1000809" }, label = "仏像", icon = "religious-buddhist" },
		cathedral = { group = "religion", wd = { "Q2977" }, label = "大聖堂", icon = "religious-christian" },
		chapel = { group = "religion", wd = { "Q108325" }, label = "礼拝堂", icon = "religious-christian" },
		chapel_shrine = { group = "religion", wd = { "Q14552192" }, label = "礼拝の祠" },
		church = { group = "religion", wd = { "Q16970", "Q580499" }, label = "教会", icon = "religious-christian" },
		fire_temple = { group = "religion", wd = { "Q115278" }, label = "拝火神殿" },
		gurdwara = { group = "religion", wd = { "Q337986" }, label = "グルドワーラー" },
		hindu_temple = { group = "religion", wd = { "Q842402" }, label = "ヒンドゥー教寺院" },
		lak_mueang = { group = "religion", wd = { "Q974127" }, label = "ラックムアン" },
		minaret = { group = "religion", wd = { "Q48356" }, label = "ミナレット" },
		monastery = { group = "religion", wd = { "Q44613", "Q160742" }, label = "修道院" },
		mosque = { group = "religion", wd = { "Q32815" }, label = "モスク", icon = "religious-muslim" },
		nunnery = { group = "religion", wd = { "Q6021560" }, label = "女子僧院" },
		pagoda = { group = "religion", wd = { "Q199451" }, label = "仏塔" },
		pilgrimage_site = { group = "religion", wd = { "Q15135589" }, label = "巡礼地" },
		sanctuary = { group = "religion", wd = { "Q29553" }, label = "聖域" },
		shinto_shrine = { group = "religion", wd = { "Q845945" }, label = "神社", icon = "religious-shinto" },
		shrine = { group = "religion", wd = { "Q697295" }, label = "聖堂" },
		stupa = { group = "religion", wd = { "Q180987" }, label = "卒塔婆" },
		synagogue = { group = "religion", wd = { "Q34627" }, label = "シナゴーグ", icon = "religious-jewish" },
		temple = { group = "religion", wd = { "Q44539", "Q927825", "Q58621988" }, label = "寺院" },
		wat = { group = "religion", wd = { "Q427287" }, label = "ワット" },
		wayside_cross = { group = "religion", wd = { "Q2309609" }, label = "ウェイサイド・クロス" },
		wayside_shrine = { group = "religion", wd = { "Q3395121", "Q12661150" }, label = "祠" },
		religion = { alias = "religious_site", group = "religion", wd = { "Q1370598" }, label = "宗教施設" },

		-- sights: natural

		animal_stable = { group = "nature", wd = { "Q1207909" }, label = "畜舎" },
		aquarium = { group = "nature", wd = { "Q2281788" }, label = "水族館" },
		bay = { group = "nature", wd = { "Q39594", "Q17018380" }, label = "湾" },
		botanical_garden = { group = "nature", wd = { "Q167346" }, label = "植物園" },
		canal = { group = "nature", wd = { "Q12284" }, label = "運河" },
		canyon = { group = "nature", wd = { "Q150784" }, label = "峡谷" },
		cape = { group = "nature", wd = { "Q185113" }, label = "岬" },
		cave = { group = "nature", wd = { "Q35509" }, label = "洞窟" },
		cliff = { group = "nature", wd = { "Q107679" }, label = "崖" },
		coast = { group = "nature", wd = { "Q93352" }, label = "海岸" },
		crater = { group = "nature", wd = { "Q3240715" }, label = "クレーター" },
		crocodile_farm = { group = "nature", wd = { "Q25691" }, label = "ワニ農場" },
		depression = { group = "nature", wd = { "Q190429" }, label = "凹地" },
		desert = { group = "nature", wd = { "Q8514" }, label = "砂漠" },
		dog_park = { group = "nature", wd = { "Q38516" }, label = "ドッグラン" },
        dolphinarium = { group = "nature", wd = { "Q491675" }, label = "イルカ水族館" },
		dune = { group = "nature", wd = { "Q25391" }, label = "砂丘" },
		dyke = { group = "nature", wd = { "Q105190" }, label = "堤防" },
		farm = { group = "nature", wd = { "Q131596" }, label = "農場" },
		fish_pond = { group = "nature", wd = { "Q1265665" }, label = "養魚場" },
		fjord = { group = "nature", wd = { "Q45776" }, label = "フィヨルド" },
		forest = { group = "nature", wd = { "Q4421" }, label = "森" },
		garden = { group = "nature", wd = { "Q1107656" }, label = "庭" },
		geyser = { group = "nature", wd = { "Q83471" }, label = "間欠泉" },
		glacier = { group = "nature", wd = { "Q35666" }, label = "氷河" },
		gulf = { group = "nature", wd = { "Q1322134" }, label = "湾" },
		habitat = { group = "nature", label = "生息地" },
		hill = { group = "nature", wd = { "Q54050" }, label = "丘" },
		hot_spring = { group = "nature", wd = { "Q177380" }, label = "温泉" },
		island = { group = "nature", wd = { "Q23442" }, label = "島" },
		lagoon = { group = "nature", wd = { "Q187223" }, label = "ラグーン" },
		lake = { group = "nature", wd = { "Q23397" }, label = "湖" },
		landscape = { group = "nature", wd = { "Q107425" }, label = "景観" },
		mangrove = { group = "nature", wd = { "Q19756" }, label = "マングローブ" },
		mountain = { group = "nature", wd = { "Q8502" }, label = "山" },
		mountain_chain = { group = "nature", wd = { "Q2624046" }, label = "連山" },
		mountain_pass = { group = "nature", wd = { "Q133056" }, label = "峠" },
		mountain_range = { group = "nature", wd = { "Q46831" }, label = "山脈" },
		national_park = { group = "nature", wd = { "Q46169" }, label = "国立公園" },
		natural_heritage = { group = "nature", wd = { "Q386426" }, label = "自然遺産" },
		nature_reserve = { group = "nature", wd = { "Q158454", "Q179049", "Q473972", "Q20268756" }, label = "自然保護区" },
		oasis = { group = "nature", wd = { "Q43742" }, label = "オアシス" },
		palaeontological_site = { group = "nature", wd = { "Q9096832" }, label = "古生物学的遺跡" },
		park = { group = "nature", wd = { "Q22698", "Q728904" }, label = "公園" },
		peninsula = { group = "nature", wd = { "Q34763" }, label = "半島" },
		plantation = { group = "nature", wd = { "Q188913" }, label = "プランテーション" },
		plateau = { group = "nature", wd = { "Q75520" }, label = "高原" },
		protected_area = { alias = "protectorate", group = "nature", wd = { "Q473972" }, label = "保護地域" },
		reef = { group = "nature", wd = { "Q184358" }, label = "暗礁" },
		reservoir = { group = "nature", wd = { "Q131681" }, label = "貯水池" },
		river = { group = "nature", wd = { "Q4022" }, label = "川" },
		river_mouth = { group = "nature", wd = { "Q1233637" }, label = "河口" },
		rock = { group = "nature", wd = { "Q1404150" }, label = "岩石層" },
		sea = { group = "nature", wd = { "Q165" }, label = "海" },
		spring = { group = "nature", wd = { "Q124714" }, label = "泉" },
		steppe = { group = "nature", wd = { "Q123991" }, label = "ステップ地帯" },
		strait = { group = "nature", wd = { "Q37901" }, label = "海峡" },
		stream = { group = "nature", wd = { "Q47521" }, label = "小川" },
		stud = { group = "nature", wd = { "Q108696" }, label = "種馬飼育場" },
		summit = { group = "nature", wd = { "Q207326" }, label = "頂" },
		tree = { group = "nature", wd = { "Q10884" }, label = "木" },
		valley = { group = "nature", wd = { "Q39816" }, label = "谷" },
		volcano = { group = "nature", wd = { "Q8072" }, label = "火山" },
		waterfall = { group = "nature", wd = { "Q34038" }, label = "滝" },
		wetland = { group = "nature", wd = { "Q170321" }, label = "湿地" },
		zoo = { group = "nature", wd = { "Q43501" }, label = "動物園" },
		nature = { group = "nature", wd = { "Q7860" }, label = "自然環境" },

		-- sights: arts, historic

		amphitheater =  { group = "see", wd = { "Q54831" }, label = "円形劇場" },
		aqueduct = { group = "see", wd = { "Q474" }, label = "用水路" },
		archaeological_site = { group = "see", wd = { "Q839954" }, label = "遺跡" },
		architecture = { group = "see", wd = { "Q12271" }, label = "建築" },
		archive = { group = "see", wd = { "Q166118", "Q635719", "Q27032363" }, label = "アーカイブ" },
		artwork = { group = "see", wd = { "Q838948" }, label = "芸術作品" },
		barracks = { group = "see", wd = { "Q131263" }, label = "バラック" },
		boat_lift = { group = "see", wd = { "Q14908" }, label = "船舶昇降機" },
		bridge = { group = "see", wd = { "Q12280" }, label = "橋" },
		building = { group = "see", wd = { "Q41176", "Q811979" }, label = "建造物" },
		building_complex = { group = "see", wd = { "Q1497364", "Q18247357" }, label = "建築複合体" },
		bunker = { group = "see", wd = { "Q91122" }, label = "掩体壕" },
		cannon = { group = "see", wd = { "Q81103" }, label = "キャノン砲" },
		castle = { group = "see", wd = { "Q23413" }, label = "城" },
		cellar = { group = "see", wd = { "Q234852" }, label = "地下室" },
		cemetery = { alias = "necropolis", group = "see", wd = { "Q39614" }, label = "墓地、ネクロポリス" },
		chateau = { alias = "château", group = "see", wd = { "Q751876" }, label = "シャトー" },
		city_center = { group = "see", wd = { "Q1468524" }, label = "副都心" },
		city_wall = { group = "see", wd = { "Q16748868" }, label = "市壁" },
		collection = { group = "see", wd = { "Q2668072", "Q7328910" }, label = "作品集" },
		column = { group = "see", wd = { "Q4817", "Q51845395", "Q1930585" }, label = "柱、塔" }, -- 248と違いを明確に
		communication_tower = { group = "see", wd = { "Q11166728", "Q1798641" }, label = "通信塔" },
		crematorium = { group = "see", wd = { "Q157570" }, label = "火葬場" },
		cultural_heritage = { group = "see", wd = { "Q210272" }, label = "文化遺産" },
		dam = { group = "see", wd = { "Q12323" }, label = "ダム" },
		embankment_dam = { group = "see", wd = { "Q1244922" }, label = "フィルダム" },
		exhibition = { group = "see", wd = { "Q464980" }, label = "展覧会" },
		factory = { group = "see", wd = { "Q83405" }, label = "工場" },
		fort = { group = "see", wd = { "Q57831" }, label = "要塞" },
		fountain = { group = "see", wd = { "Q483453" }, label = "噴水" },
		gallery = { group = "see", wd = { "Q1007870" }, label = "画廊", icon = "art-gallery" },
		gate = { group = "see", wd = { "Q53060" }, label = "門" },
		ghost_town = { group = "see", wd = { "Q74047" }, label = "廃村" },
		graduation_tower = { group = "see", wd = { "Q1541226" }, label = "グラディアヴェルク" },
		grave = { group = "see", wd = { "Q173387" }, label = "墓" },
		hall = { group = "see", wd = { "Q240854" }, label = "ホール" },
		handicraft = { group = "see", wd = { "Q52105" }, label = "生息地" },
		historic_district = { group = "see", wd = { "Q15243209" }, label = "歴史地区", icon = "historic" },
		house = { group = "see", wd = { "Q3947" }, label = "住宅" },
		hydraulic_structure = { group = "see", wd = { "Q2466889" }, label = "水利施設" },
		landmark = { group = "see", wd = { "Q2319498" }, label = "ランドマーク" },
		lighthouse = { group = "see", wd = { "Q39715" }, label = "燈台" },
		lock = { group = "see", wd = { "Q105731" }, label = "閘門" },
		mausoleum = { group = "see", wd = { "Q162875" }, label = "廟" },
		memorial = { group = "see", wd = { "Q5003624" }, label = "記念物" },
		mill = { group = "see", wd = { "Q44494" }, label = "粉砕機" },
		mine = { group = "see", wd = { "Q820477" }, label = "鉱山" }, -- including surface mining
		mining_museum = { group = "see", wd = { "Q819426" }, label = "鉱業博物館" },
		monument = { group = "see", wd = { "Q4989906" }, label = "モニュメント" },
		museum = { group = "see", wd = { "Q33506" }, label = "博物館、美術館" },
		museum_ship = { group = "see", wd = { "Q575727" }, label = "博物館船" },
		obelisk = { group = "see", wd = { "Q170980" }, label = "オベリスク" },
		observatory = { group = "see", wd = { "Q1254933", "Q62832" }, label = "天文台" },
		old_town = { group = "see", wd = { "Q676050" }, label = "旧市街", icon = "historic" },
		open_air_museum = { group = "see", wd = { "Q756102" }, label = "野外博物館" },
		palace = { group = "see", wd = { "Q16560" }, label = "宮殿" },
		pavilion = { alias = "arbor", group = "see", wd = { "Q276173", "Q23457088", "Q961082" }, label = "パビリオン、東屋" },
		pedestrian = { group = "see", wd = { "Q369730" }, label = "歩行者天国" },
		planetarium = { group = "see", wd = { "Q148319" }, label = "プラネタリウム" },
		power = { group = "see", wd = { "Q159719" }, label = "発電所" }, -- power station, transformers, towers etc.
		promenade = { group = "see", wd = { "Q787113" }, label = "遊歩道" },
		pyramid = { group = "see", wd = { "Q12516" }, label = "ピラミッド" },
		quarry = { group = "see", wd = { "Q15115254" }, label = "石切場" },
		road = { group = "see", wd = { "Q34442", "Q83620" }, label = "道" }, -- including street and lane
		rock_art = { group = "see", wd = { "Q1211146" }, label = "洞窟壁画" },
		ruins = { group = "see", wd = { "Q109607" }, label = "廃墟" },
		shipyard = { group = "see", wd = { "Q190928" }, label = "造船所" },
		spaceport = { group = "see", wd = { "Q194188" }, label = "発射場" },
		square = { group = "see", wd = { "Q174782" }, label = "広場" },
		statue = { group = "see", wd = { "Q179700" }, label = "塑像" },
		stele = { group = "see", wd = { "Q178743" }, label = "石碑" },
		stolperstein = { group = "see", wd = { "Q314003" }, label = "躓きの石" },
		technical_monument = { group = "see", wd = { "Q1516537" }, label = "技術的記念物" },
		tomb = { group = "see", wd = { "Q381885", "Q6023295" }, label = "墓" },
		tower = { group = "see", wd = { "Q12518" }, label = "塔" }, -- 194と違いを明確に
		town_hall = { group = "see", wd = { "Q543654" }, label = "市庁舎" },
		tumulus = { group = "see", wd = { "Q34023" }, label = "古墳" },
		viaduct =  { group = "see", wd = { "Q181348" }, label = "高架橋" },
		wall =  { group = "see", wd = { "Q42948" }, label = "壁" },
		war_grave = { group = "see", wd = { "Q90717531" }, label = "戦没者墓地" },
		watermill = { group = "see", wd = { "Q185187" }, label = "水車小屋" },
		weather_station = { group = "see", wd = { "Q190107" }, label = "気象台" },
		weir = { group = "see", wd = { "Q1066997" }, label = "堰" },
		well = { group = "see", wd = { "Q43483" }, label = "井戸" },
		windmill = { group = "see", wd = { "Q38720" }, label = "風車" },
		wreck = { group = "see", wd = { "Q852190" }, label = "難破船" },
		-- group types
		see = { group = "see", wd = { "Q570116" }, label = "観光名所" },

		-- culture

		arena = { group = "do", wd = { "Q641226" }, label = "アリーナ" },
		arts_center = { group = "do", wd = { "Q2190251" }, label = "芸術センター" },
		bird_watching = { group = "do", wd = { "Q685629" }, label = "バードウォッチング" },
		bullring = { group = "do", wd = { "Q1193438" }, label = "闘牛場" },
		cabaret = { group = "do", wd = { "Q131183" }, label = "キャバレー" },
		cinema = { group = "do", wd = { "Q41253" }, label = "映画館" },
		circus = { group = "do", wd = { "Q47928" }, label = "サーカス" },
		concert_hall = { group = "do", wd = { "Q1060829" }, label = "コンサートホール" },
		conference_center = { group = "do", wd = { "Q1378975" }, label = "展示場" },
		cultural_center = { group = "do", wd = { "Q1329623" }, label = "文化センター" },
		edutainment = { group = "do", wd = { "Q1153173" }, label = "エデュテインメント" },
		event = { group = "do", wd = { "Q1190554" }, label = "イベント" },
		event_venue = { group = "do", wd = { "Q18674739" }, label = "イベント会場" },
		fair = { group = "do", wd = { "Q57305", "Q2948561" }, label = "見本市" },
		festival = { group = "do", wd = { "Q132241" }, label = "祭" },
		heritage_railway = { group = "do", wd = { "Q420962" }, label = "保存鉄道" },
		karaoke = { group = "do", wd = { "Q229345" }, label = "カラオケ" },
		[ "multi-purpose_hall" ] = { group = "do", wd = { "Q1763828", "Q2400020" }, label = "多目的ホール" },
		music = { group = "do", wd = { "Q638" }, label = "音楽" }, -- different types of music theaters
		opera_house = { group = "do", wd = { "Q153562" }, label = "オペラハウス" },
		puppet_theater = { group = "do", wd = { "Q3982337" }, label = "人形劇場" },
		theater = { group = "do", wd = { "Q11635", "Q24354" }, label = "劇場", icon = "theatre" }, -- speech theater, theater in general
		themed_travel = { group = "do", label = "テーマ別旅行" },
		wildlife_observation = { group = "do", wd = { "Q28455557" }, label = "野生動物観察" },

		-- recreation

		amusement_park = { group = "do", wd = { "Q194195" }, label = "遊園地" },
		attraction = { group = "do", wd = { "Q2800000" }, label = "アトラクション" },
		ballooning = { group = "do", wd = { "Q805325" }, label = "熱気球競技" },
		casino = { group = "do", wd = { "Q133215" }, label = "カジノ" },
		entertainment = { group = "do", wd = { "Q173799" }, label = "娯楽施設" },
		escape_game = { group = "do", wd = { "Q1201679" }, label = "脱出ゲーム" },
		horse_riding = { group = "do", wd = { "Q179226" }, label = "乗馬" },
		massage = { group = "do", wd = { "Q179415" }, label = "マッサージサロン" },
        picnic = { group = "do", wd = { "Q506294" }, label = "ピクニック", icon = "picnic-site" },
		playground = { group = "do", wd = { "Q11875349" }, label = "遊び場" },
		public_bath = { group = "do", wd = { "Q785952" }, label = "公衆浴場" },
		ropes_course = { group = "do", wd = { "Q1939700" }, label = "フィールドアスレチック" },
		sauna = { group = "do", wd = { "Q57036" }, label = "サウナ" },
		spa = { alias = "wellness", group = "do", wd = { "Q6882870" }, label = "スパ" },
		theme_park = { group = "do", wd = { "Q2416723" }, label = "テーマパーク" },
		water_park = { group = "do", wd = { "Q740326", "Q118559331" }, label = "ウォーターパーク" },
		youth_center = { group = "do", wd = { "Q1302299" }, label = "青少年クラブ" },

		-- sports and fitness

		["9pin"] = { group = "do", wd = { "Q706199" }, label = "ナインピン" },
		["10pin"] = { alias = "bowling", group = "do", wd = { "Q172809" }, label = "ボーリング", icon = "bowling-alley" },
		athletics_track = { group = "do", wd = { "Q1004435", "Q37025296", "Q121072018" }, label = "競走用トラック" },
		badminton = { group = "do", wd = { "Q7291" }, label = "バドミントン・コート" },
		basketball_court = { group = "do", wd = { "Q2341939" }, label = "バスケットボール・コート" },
		beach = { group = "do", wd = { "Q40080" }, label = "ビーチ" },
		beachvolleyball = { group = "do", wd = { "Q4543" }, label = "ビーチバレー" },
		bicycle_route = { group = "do", wd = { "Q353027", "Q102307360" }, label = "サイクリングロード" },
		billiards = { group = "do", wd = { "Q3341285" }, label = "ビリヤード" },
		bmx = { group = "do", wd = { "Q215184" }, label = "BMX" },
		boat_rental = { group = "do", wd = { "Q25384001" }, label = "レンタルボート" },
		bobsleigh = { group = "do", wd = { "Q177275" }, label = "そり滑り" },
		bouldering = { group = "do", wd = { "Q852989" }, label = "ボルダリング" },
		boules = { group = "do", wd = { "Q895060" }, label = "ブール" },
		bungee_jumping = { group = "do", wd = { "Q193847" }, label = "バンジージャンプ" },
		canoe = { group = "do", wd = { "Q171529" }, label = "舟" }, -- カヌー、カヤック
		canyoning = { group = "do", wd = { "Q206091" }, label = "キャニオニング" },
		city_beach = { group = "do", wd = { "Q7900097" }, label = "人工海浜" }, -- 含：ビーチクラブ
		climbing = { group = "do", wd = { "Q22857" }, label = "登山" },
		court = { group = "do", wd = { "Q41487" }, label = "裁判所、法廷" },
		cricket = { group = "do", wd = { "Q5375" }, label = "クリケット" },
		cycling = { group = "do", wd = { "Q53121" }, label = "サイクリング" },
		dive_center = { group = "do", wd = { "Q3664857" }, label = "ダイブ・センター" },
		downhill = { group = "do", wd = { "Q319899", "Q121071424" }, label = "ダウンヒル", icon = "skiing" }, -- アルペン・ダウンヒルスキー
		equestrian = { group = "do", wd = { "Q902378" }, label = "乗馬" },
		extreme_sports = { group = "do", wd = { "Q309162" }, label = "エクストリームスポーツ" },
		fishing = { group = "do", wd = { "Q14373" }, label = "釣り" },
		fitness_center = { alias = "gym", group = "do", wd = { "Q1065656", "Q30750411" }, label = "アスレチッククラブ、ジム", icon = "fitness-centre" },
		football_pitch = { group = "do", wd = { "Q105755419" }, label = "サッカー場" },
		gliding = { group = "do", wd = { "Q624161" }, label = "滑空" },
		golf = { group = "do", wd = { "Q5377" }, label = "ゴルフ" },
		hiking = { alias = "trekking", group = "do", wd = { "Q12014035" }, label = "ハイキング" },
		hillwalking = { group = "do", wd = { "Q1762646" }, label = "トレッキング" },
		horse_racing = { group = "do", wd = { "Q187916" }, label = "競馬" },
		hunting = { group = "do", wd = { "Q36963" }, label = "狩猟" },
		ice_hockey = { group = "do", wd = { "Q41466" }, label = "アイスホッケー" },
		ice_rink = { group = "do", wd = { "Q1282870" }, label = "スケートリンク" },
		ice_skating = { group = "do", wd = { "Q779272" }, label = "アイススケート" },
		ice_stadium = { group = "do", wd = { "Q12019965" }, label = "スケート場" },
		indoor_pool = { group = "do", wd = { "Q357380" }, label = "屋内プール" },
		karting = { group = "do", wd = { "Q192420" }, label = "ゴーカート" },
		kitesurfing = { group = "do", wd = { "Q219554" }, label = "カイトサーフィン" },
		leisure_center = { group = "do", wd = { "Q30313989" }, label = "遊園地、レジャー施設" },
		mountain_biking = { group = "do", wd = { "Q520611", "Q223705" }, label = "マウンテンバイク" },
		minigolf = { group = "do", wd = { "Q754796" }, label = "パターゴルフ" },
		motocross = { group = "do", wd = { "Q215862" }, label = "モトクロス" },
		nordic = { group = "do", wd = { "Q216613" }, label = "ノルディック・スキー、スカンジナビアン・スキー" }, -- クロスカントリー・スキー、トレイル・スキー
		orienteering = { group = "do", wd = { "Q29358" }, label = "オリエンテーリング" },
		outdoor_pool = { group = "do", wd = { "Q13586493" }, label = "屋外プール" },
		parachuting = { alias = "skydiving", group = "do", wd = { "Q193210" }, label = "スカイダイビング" },
		paragliding = { group = "do", wd = { "Q178380" }, label = "パラグライダー" },
		polo = { group = "do", wd = { "Q134211" }, label = "ポロ" },
		quad_bike = { group = "do", wd = { "Q3926537" }, label = "四輪バギー" },
		racetrack = { group = "do", wd = { "Q1777138" }, label = "レース場" },
		rafting = { group = "do", wd = { "Q207238" }, label = "筏競技" }, -- including whitewater rafting
		roller_skating = { group = "do", wd = { "Q1707432" }, label = "ローラースケート" }, -- including inline roller skating
		rowing = { group = "do", wd = { "Q159354" }, label = "競艇" },
		running = { group = "do", wd = { "Q3694569" }, label = "トラック競争、徒競走" },
		sailing = { group = "do", wd = { "Q192520" }, label = "ヨット" },
		sandboarding = { group = "do", wd = { "Q570459" }, label = "サンドボーディング" },
		scuba_diving = { group = "do", wd = { "Q1096878" }, label = "ダイビング" },
		shooting_range = { group = "do", wd = { "Q521839" }, label = "射撃場、射的場" },
		skatepark = { group = "do", wd = { "Q909906" }, label = "スケート競技場" },
		ski_jumping = { group = "do", wd = { "Q7718" }, label = "スキージャンプ" },
		ski_school = { group = "do", wd = { "Q2292514" }, label = "スキー教室" },
		skitour = { group = "do", wd = { "Q1075998" }, label = "山岳スキー" },
		sledding = { group = "do", wd = { "Q3266340" }, label = "そり" },
		snorkeling = { group = "do", wd = { "Q2471422" }, label = "シュノーケリング" },
		snow_park = { group = "do", wd = { "Q3141488" }, label = "ゲレンデ" },
		soccer = { group = "do", wd = { "Q2736" }, label = "サッカー" },
		summer_toboggan = { group = "do", wd = { "Q3266345" }, label = "サマーボブスレー" },
		sports = { group = "do", wd = { "Q349" }, label = "スポーツ" },
		sports_venue = { group = "do", wd = { "Q1076486", "Q121071543", "Q120169931" }, label = "スポーツ施設" },
		squash = { group = "do", wd = { "Q121072153", "Q121085278" }, label = "スカッシュ" },
		stadium = { group = "do", wd = { "Q483110", "Q37025296" }, label = "スタジアム" },
		surfing = { group = "do", wd = { "Q159992" }, label = "サーフィン" },
		swimming = { group = "do", wd = { "Q6388" }, label = "水泳" },
		swimming_pool = { group = "do", wd = { "Q200023" }, label = "水泳プール" },
		tennis = { alias = "tennis_court", group = "do", wd = { "Q847", "Q741118" }, label = "テニスコート" },
		toboggan = { group = "do", wd = { "Q56611604" }, label = "リュージュ走路" },
		tour = { group = "do", label = "旅行" },
		trail = { alias = "hiking_trail", wd = { "Q2143825" }, group = "do", label = "ハイキングコース" },
		triathlon = { group = "do", wd = { "Q10980" }, label = "トライアスロン" },
		velodrome = { group = "do", wd = { "Q830528" }, label = "自転車競技場", icon = "racetrack-cycling" },
		wakeboarding = { group = "do", wd = { "Q376040" }, label = "ウェイクボート" },
		water_skiing = { group = "do", wd = { "Q472827" }, label = "水上スキー" },
		water_sports = { group = "do", wd = { "Q61065" }, label = "ウォータースポーツ" },
		winter_sports = { group = "do", wd = { "Q204686" }, label = "ウィンタースポーツ" },
		-- group types
		["do"] = { group = "do", label = "アクティビティ" },

		-- shopping

		alcohol_shop = { group = "buy", wd = { "Q2632011" }, label = "酒屋" },
		antiquarian = { group = "buy", wd = { "Q582794" }, label = "古本屋" },
		atm = { group = "buy", wd = { "Q81235" }, label = "ATM" },
		bakery = { group = "buy", wd = { "Q274393" }, label = "パン屋、ベーカリー" },
		bank = { group = "buy", wd = { "Q22687" }, label = "銀行" },
		beverages = { group = "buy", wd = { "Q47504516" }, label = "飲料店" },
		bike_shop = { group = "buy", wd = { "Q26721034" }, label = "自転車店" },
		book_seller = { alias = "book_shop", group = "buy", wd = { "Q200764" }, label = "書店、本屋" },
		boutique = { group = "buy", wd = { "Q1068824" }, label = "ブティック" },
		business_park = { group = "buy", wd = { "Q338313" }, label = "商業エリア" },
		butchery = { group = "buy", wd = { "Q13164546" }, label = "精肉店" },
		carpet_shop = { group = "buy", wd = { "Q47516346" }, label = "カーペットショップ" },
		cheesery = { group = "buy", wd = { "Q3088348" }, label = "チーズ工場" },
		chemist = { alias = "drugstore", group = "buy", wd = { "Q1260046" }, label = "ドラッグストア、薬屋" },
		collector_shop = { group = "buy", label = "コレクターショップ" },
		cosmetics_shop = { group = "buy", wd = { "Q47508166" }, label = "化粧品店、コスメショップ" },
		crafts_shop = { group = "buy", wd = { "Q101061294" }, label = "手工芸品店、クラフトショップ" },
		currency_exchange = { group = "buy", wd = { "Q2002539" }, label = "両替所" },
		delicatessen = { group = "buy", wd = { "Q3231410" }, label = "デリ、高級総菜屋" },
		department_store = { group = "buy", wd = { "Q216107" }, label = "デパート、百貨店" },
		["duty-free_shop"] = { group = "buy", wd = { "Q545609" }, label = "免税店" },
		fashion_store = { alias = "clothing_store", group = "buy", wd = { "Q2090555" }, label = "ファッション店、洋服屋", icon = "clothing-store" },
		farm_shop = { group = "buy", wd = { "Q1371823" }, label = "農産物直売所、道の駅" },
		flea_market = { group = "buy", wd = { "Q385870" }, label = "フリーマーケット" },
		florist = { group = "buy", wd = { "Q10431511" }, label = "生花店、花屋" },
		grocery = { group = "buy", wd = { "Q1295201" }, label = "食料品店、食糧品店、食品店、八百屋、魚屋、乾物屋、雑貨店" },
		hairdresser = { group = "buy", wd = { "Q95856773" }, label = "美容院、ヘアサロン、理髪店、理容院" },
		industrial_park = { group = "buy", wd = { "Q1662100" }, label = "工業団地" },
		jewellery = { group = "buy", wd = { "Q20708021" }, label = "宝石商、宝石店", icon = "jewelry-store" },
		kiosk = { group = "buy", wd = { "Q693369" }, label = "キオスク、売店" },
		mall = { group = "buy", wd = { "Q11315", "Q31374404" }, label = "ショッピングセンター、ショッピングモール" },
		market = { group = "buy", wd = { "Q37654" }, label = "市場" },
		music_shop = { group = "buy", wd = { "Q24284215" }, label = "楽器店" },
		optician = { group = "buy", wd = { "Q80144507" }, label = "眼鏡店" },
		outdoor_retailer = { group = "buy", label = "グローブトロッター" },
		outlet = { group = "buy", wd = { "Q76470" }, label = "アウトレットモール" },
		pastry_shop = { alias = "confectionery", group = "buy", wd = { "Q47505416" }, label = "ケーキ屋、洋菓子屋、焼き菓子屋" },
		photo_store = { group = "buy", wd = { "Q57262241" }, label = "写真屋、写真スタジオ" },
		second_hand = { group = "buy", wd = { "Q2925872" }, label = "リサイクルストア" },
		shoe_shop = { group = "buy", wd = { "Q7500021" }, label = "靴屋", icon = "shoe" },
		shop = { group = "buy", wd = { "Q213441" }, label = "店" },
		shopping_district = { group = "buy", wd = { "Q27095213" }, label = "商業地区" },
		shopping_street = { group = "buy", wd = { "Q21000333" }, label = "商店街、仲見世、アーケード" },
		souvenir_shop = { group = "buy", wd = { "Q865693" }, label = "お土産屋、ギフト・ショップ" },
		sports_shop = { group = "buy", wd = { "Q47516567" }, label = "スポーツ用品店" },
		supermarket = { group = "buy", wd = { "Q180846" }, label = "スーパーマーケット" },
		ticket_shop = { alias = "box_office", group = "buy", wd = { "Q47519615", "Q877435" }, label = "チケット店" },
		vending_machine = { group = "buy", wd = { "Q211584" }, label = "自動販売機" },
		watersports_shop = { group = "buy", label = "ウォータースポーツ用品店" },
		-- group types
		buy = { group = "buy", label = "買い物" },

		-- cuisine, eating

		agriculture = { group = "eat", wd = { "Q11451" }, label = "農業" },
		bistro = { group = "eat", wd = { "Q866742" }, label = "ビストロ、大衆食堂" },
		brasserie = { group = "eat", wd = { "Q1581509" }, label = "ブラッスリー" },
		cafe = { group = "eat", wd = { "Q30022" }, label = "カフェ、喫茶店" },
		cafeteria = { group = "eat", wd = { "Q8463304" }, label = "カフェテリア、食堂" },
		canteen = { group = "eat", wd = { "Q54957790" }, label = "カフェテリア、簡易食堂" }, -- カフェテリアも含む
		community_kitchen = { group = "eat", wd = { "Q28854744" }, label = "共同台所、共同キッチン" },
		fast_food = { group = "eat", wd = { "Q1751429" }, label = "ファーストフード店" },
		food = { group = "eat", wd = { "Q2095", "Q736427" }, label = "食品、主食" },
		ice_cream = { group = "eat", wd = { "Q1311064" }, label = "アイスクリーム専門店" },
		izakaya = { group = "eat", wd = { "Q1193068" }, label = "居酒屋、飲み屋、大衆酒場" },
		pizzeria = { group = "eat", wd = { "Q1501212" }, label = "ピッツェリア", icon = "restaurant-pizza" },
		restaurant = { group = "eat", wd = { "Q11707" }, label = "レストラン、食事処" },
		seafood_restaurant = { alias = "seafood", group = "eat", wd = { "Q17102985" }, label = "海鮮食堂、シーフードレストラン", icon = "restaurant-seafood" },
		snack_bar = { group = "eat", wd = { "Q1318768" }, label = "フードカウンター、スナックバー" },
		steak_house = { group = "eat", wd = { "Q3109696" }, label = "ステーキハウス" },
		street_food = { group = "eat", wd = { "Q1316209" }, label = "屋台、屋台飯" },
		takeaway = { group = "eat", wd = { "Q154383", "Q506946" }, label = "テイクアウト、出前、持ち帰り" },
		tavern = { group = "eat", wd = { "Q154250", "Q2387565" }, label = "居酒屋、酒場" },
		teahouse = { group = "eat", wd = { "Q1072166" }, label = "茶屋、茶館、茶房" },
		-- group types
		eat = { group = "eat", wd = { "Q27038993", "Q27077054" }, label = "食事処" },

		-- drinking, going out

		bar = { group = "drink", wd = { "Q187456" }, label = "バー" },
		beer_garden = { group = "drink", wd = { "Q857909" }, label = "ビアガーデン", icon = "beer" },
		brewery = { group = "drink", wd = { "Q131734" }, label = "醸造所" },
		club = { group = "drink", label = "クラブ" },
		discotheque = { group = "drink", wd = { "Q1228895" }, label = "ディスコ" },
		distillery = { group = "drink", wd = { "Q1251750" }, label = "蒸留所" },
		drinking_hall = { group = "drink", wd = { "Q4101440" }, label = "酒宴、酒盛り" },
		drinking_water = { group = "drink", wd = { "Q7892" }, label = "飲料水、飲み水" },
		nightclub = { group = "drink", wd = { "Q622425" }, label = "ナイトクラブ" },
		pub = { group = "drink", wd = { "Q19754932", "Q12341378" }, label = "パブ" },
		vineyard = { group = "drink", wd = { "Q22715" }, label = "ぶどう園、ぶどう畑" },
		winery = { group = "drink", wd = { "Q20181766" }, label = "ワイナリー" },
		-- group types
		drink = { group = "drink", wd = { "Q5307737" }, label = "酒屋" },

		-- accommodation

		appartment = { group = "sleep", wd = { "Q617839" }, label = "短期賃貸マンション" },
		alpine_hut = { group = "sleep", wd = { "Q182676" }, label = "山小屋" },
		bed_and_bike = { group = "sleep", label = "バイク旅向け宿" },
		bnb = { group = "sleep", subtype = "y", wd = { "Q367914" }, label = "ベッド＆ブレックファスト、民宿", icon = "lodging" },
		boarding_house = { group = "sleep", subtype = "y", wd = { "Q1558858", "Q1065252" }, label = "ペンション" },
		campsite = { group = "sleep", wd = { "Q832778" }, label = "キャンプ場、テントサイト" },
		caravan_site = { group = "sleep", label = "オートキャンプ場" },
		chalet = { group = "sleep", label = "別荘、山荘" },
		ecolodge = { group = "sleep", wd = { "Q3577646" }, label = "エコロッジ" },
		group_accomodation = { group = "sleep", label = "団体宿泊施設" },
		guest_house = { group = "sleep", wd = { "Q2460422" }, label = "ゲストハウス、民宿、民泊" },
		holiday_flat = { group = "sleep", wd = { "Q336532" }, label = "ホリデーフラット" },
		hostel = { group = "sleep", wd = { "Q654772" }, label = "ホステル、ユースホステル", icon = "lodging" },
		hotel = { group = "sleep", wd = { "Q27686", "Q63099748" }, label = "ホテル、旅館", icon = "lodging" },
		hotel_garni = { group = "sleep", subtype = "y", wd = { "Q1631103" }, label = "小規模ビジネスホテル", icon = "lodging" },
		motel = { group = "sleep", wd = { "Q216212" }, label = "モーテル", icon = "lodging" },
		resort = { group = "sleep", wd = { "Q875157" }, label = "リゾートホテル" },
		wilderness_hut = { group = "sleep", wd = { "Q17087359" }, label = "野小屋、掘っ立て小屋" },
		youth_hostel = { group = "sleep", wd = { "Q1589077" }, label = "ユースホステル" },
		-- group types
		sleep = { group = "sleep", wd = { "Q5056668" }, label = "宿泊所" },

		-- people

		children = { group = "other", wd = { "Q7569" }, label = "子ども" },

		-- health

		animal_hospital = { group = "health", wd = { "Q1706476" }, label = "動物病院" },
		defibrillator = { group = "health", wd = { "Q1450682" }, label = "AED設置箇所" },
		dental_emergency_service = { group = "health", label = "休日診療歯科、歯科救急" },
		dentist = { group = "health", wd = { "Q2979300" }, label = "歯科医" },
        diving_chamber = { alias = "", group = "health", wd = { "Q549046" }, label = "ダイビング・チャンバー" },
		doctor = { alias ="surgery", group = "health", wd = { "Q718966" }, label = "診察室、医務室、救護室" },
        emergency = { alias = "emergency_department", group = "health", wd = { "Q1295316" }, label = "救急救命室" },
		emergency_medical_services = { group = "health", wd = { "Q860447" }, label = "救急隊、救急車" },
		first_aid = { group = "health", wd = { "Q133981" }, label = "応急処置、応急救護" },
		health = { group = "health", wd = { "Q12147" }, label = "健康" },
		health_center = { alias = "clinic", group = "health", wd = { "Q569500", "Q1774898" }, label = "保健所、医療センター、クリニック、診療所" },
		hospital = { group = "health", wd = { "Q16917" }, label = "病院" },
		laboratory = { group = "health", wd = { "Q483242", "Q112203425" }, label = "研究室、実験施設" },
		["medical_on-call_service"] = { group = "health", label = "往診医、訪問医" },
		naturopathy = { group = "health", wd = { "Q213403" }, label = "自然療法、民間療法" },
		nursing_home = { group = "health", wd = { "Q837142" }, label = "老人ホーム" },
		pharmacy = { group = "health", wd = { "Q13107184" }, label = "処方薬局、薬局" },
		pharmacy_on_standby_duty = { group = "health", label = "休日処方せん、夜間処方せん" },
		rehabilitation = { group = "health", wd = { "Q2795791" }, label = "リハビリ施設、リハビリテーション病院" },
		rescue_center = { group = "health", label = "救命救急、私費救急車" },
		veterinary = { group = "health", wd = { "Q15850915" }, label = "獣医師" },

		-- teaching & learning

		academy = { group = "other", wd = { "Q162633" }, label = "アカデミー、学術団体" },
		bookcase = { group = "other", wd = { "Q215857" }, label = "本棚" },
		college = { group = "other", wd = { "Q189004" }, label = "大学" },
		cooking_class = { group = "other", label = "料理教室" },
		education = { alias = "learn", group = "other", wd = { "Q8434" }, label = "教育" },
		folk_high_school = { group = "other", wd = { "Q170087" }, label = "フォルケホイスコーレ" },
		gymnasium = { group = "other", wd = { "Q55043" }, label = "高校" },
		institute = { group = "other", wd = { "Q1664720" }, label = "研究所" },
		kindergarten = { group = "other", wd = { "Q126807" }, label = "幼稚園" },
		language_school = { group = "other", wd = { "Q897403" }, label = "語学学校" },
		library = { group = "other", wd = { "Q7075" }, label = "図書館" },
		nursery = { group = "other", wd = { "Q20174673" }, label = "保育園" },
		school = { group = "other", wd = { "Q3914" }, label = "学校" },
		university = { group = "other", wd = { "Q3918" }, label = "大学" },

		-- administration and uncategorized

		administration = { group = "other", wd = { "Q5283295" }, label = "経営陣、経営部署" },
		business_development_agency = { group = "other", label = "経済発展企業、総合商社" },
		checkpoint = { group = "other", wd = { "Q88871664" }, label = "検問所" },
		company = { group = "other", wd = { "Q6881511" }, label = "会社" },
		consulate = { group = "other", wd = { "Q7843791" }, label = "領事館" },
		coworking_space = { group = "other", wd = { "Q97307779" }, label = "協働スペース" },
		customs = { group = "other", wd = { "Q182290" }, label = "税関" },
		cultural_organisation = { group = "other", wd = { "Q29918292" }, label = "文化団体" },
		embassy = { group = "other", wd = { "Q3917681" }, label = "大使館" },
		emergency_call = { group = "other", wd = { "Q694554" }, label = "緊急電話", icon = "emergency-phone" },
		fire_brigade = { group = "other", wd = { "Q6498663" }, label = "消防本部", icon = "fire-station" },
		government = { group = "other", wd = { "Q16831714" }, label = "官公庁" },
		guide = { group = "other", wd = { "Q14290559" }, label = "ガイド、案内人" },
		hotline = { group = "other", wd = { "Q1482145" }, label = "電話相談サービス" },
		internet_cafe = { group = "other", wd = { "Q272399" }, label = "ネットカフェ" },
		laundry = { group = "other", wd = { "Q12893467" }, label = "洗濯屋、ランドリー" },
		list = { group = "other", wd = { "Q12139612", "Q13406463" }, label = "一覧、リスト" },
		lost_and_found = { group = "other", wd = { "Q15983979" }, label = "遺失物扱取扱所、紛失物取扱所" },
		military = { group = "other", wd = { "Q8473" }, label = "軍隊" },
		mobile_telephony = { group = "other", wd = { "Q47516435" }, label = "携帯電話販売店" },
		newspaper = { group = "other", wd = { "Q11032" }, label = "新聞、新聞社" },
		office = { group = "other", wd = { "Q182060" }, label = "事業所、事務所" },
		organisation = { group = "other", wd = { "Q43229" }, label = "組織" },
		passport_office = { group = "other", label = "旅券窓口、パスポートセンター" },
		phone = { group = "other", wd = { "Q11035" }, label = "電話機", icon = "telephone" },
		police = { group = "other", wd = { "Q35535" }, label = "警察署" },
		post = { group = "other", wd = { "Q35054" }, label = "郵便局" },
		register_office = { alias = { "standesamt", "registry_office" }, group = "other", wd = { "Q745221", "Q29127138", "Q206946" }, label = "登記所、戸籍課" },
		relief_organisation = { group = "other", wd = { "Q708676" }, label = "慈善団体、公益団体" },
		roadside_assistance = { group = "other", wd = { "Q337810" }, label = "ロードサービス" },
		shelter = { group = "other", wd = { "Q7493941" }, label = "避難所" },
		toilet = { group = "other", wd = { "Q7857" }, label = "トイレ、洗面所、お手洗い、便所" },
		tour_operator = { group = "other", wd = { "Q133744" }, label = "ツアー主催者、旅行代理店" },
		tourism_authority = { group = "other", label = "観光局、観光協会" },
		tourist_information = { alias = "visitor_center", group = "other", wd = { "Q1587716", "Q18411786" }, label = "観光案内所", icon = "information" },
		travel_agency = { group = "other", wd = { "Q217107" }, label = "旅行業者、旅行代理業者" },
		weblink = { group = "other", wd = { "Q102014" }, label = "ウェブリンク" },
		wlan = { group = "other", wd = { "Q334765" }, label = "ホットスポット" },
		work = { group = "other", wd = { "Q6958747" }, label = "仕事" },
		-- group types
		other = { group = "other", label = "その他" },
		listing = { group = "other", label = "リスティング" },

		-- populated areas
		
		city = { group = "populated", wd = { "Q515" }, label = "都市" },
		fraction = { group = "populated", label = "都市の範囲" },
		holiday_resort = { group = "populated", wd = { "Q3077815" }, label = "別荘地、避暑地" },
		municipality = { group = "populated", wd = { "Q15284", "Q17376095", "Q562061" }, label = "地方都市、小都市" },
		quarter = { alias = "neighborhood", group = "populated", wd = { "Q2983893", "Q253019" }, label = "地区、街区" },
		refugee_camp = { group = "populated", wd = { "Q622499" }, label = "難民キャンプ" },
		settlement = { group = "populated", wd = { "Q486972" }, label = "集落、村落" },
		town = { group = "populated", wd = { "Q3957" }, label = "町" },
		village = { group = "populated", wd = { "Q532" }, label = "村" },

		-- views
		
		observation_tower = { group = "view", wd = { "Q1440300" }, label = "展望台、展望塔" },
		scenic_view = { group = "view", label = "Bildmotiv", icon = "景勝地" },
		viewpoint = { group = "view", wd = { "Q6017969" }, label = "見晴らし台、展望台" },

		-- areas

		adm1st = { group = "area", wd = { "Q10864048" }, label = "行政単位　レベル1" },
		adm2nd = { group = "area", wd = { "Q13220204" }, label = "行政単位　レベル2" },
		adm3rd = { group = "area", wd = { "Q13221722" }, label = "行政単位　レベル3" },
		country = { group = "area", wd = { "Q6256" }, label = "国" },
		district = { group = "area", wd = { "Q149621" }, label = "地区" },
		region = { group = "area", wd = { "Q82794" }, label = "地域、地方" },
		surroundings = { group = "area", wd = { "Q2920644" }, label = "外界、他の場所" },
		vicinity = { group = "area", wd = { "Q16968816" }, label = "周囲、近隣" },

		-- error
		
		error = { group = "error", wd = { "Q29485" }, label = "エラー" }
	}
}