--[[
	Please use only quotation marks instead of apostrophs for JSON export.
	Do not change this modul without need. A change causes the parsing of the
	majority of articles. Wishes for new types should be discussed and collected
	on Module talk:Marker utilities/Types.
	Types should conform to tags in Openstreetmap, if possible.
	New types must be entered in Template:Marker/XML and Template:vCard/XML, too.
--]]

return {
	-- administration
	moduleInterface = {
		suite  = "Marker utilities",
		sub    = "types",
		serial = "2023-11-23",
		item   = 65444106
	},

	types = {
		-- journey and mobility

		aerialway = { group = "go", wd = { "Q1424016" }, label = "ケーブルカー" },
		airline = { group = "go", wd = { "Q46970" }, label = "航空会社" },
		airport = { group = "go", wd = { "Q1248784", "Q62447", "Q644371" }, useIATA = "1", label = "空港" },
		airport_service = { group = "go", label = "空港サービス" },
		bicycle_parking = { group = "go", wd = { "Q16243822" }, label = "駐輪場" },
		bicycle_rental = { alias = "bicycle_share", group = "go", wd = { "Q10611118", "Q1358919" }, label = "レンタサイクル", icon = "bicycle-share" },
		boat_sharing = { group = "go", wd = { "Q4931514" }, label = "ボートシェアリング" },
		boat_trip = { group = "go", wd = { "Q25040412" }, label = "船旅" },
		border_control = { group = "go", wd = { "Q218719" }, label = "出入国管理" },
		bus = { alias = "bus_stop", group = "go", wd = { "Q953806", "Q494829" }, label = "バス停" },
		car_rental = { group = "go", wd = { "Q291240" }, label = "レンタカー" },
		car_repair = { group = "go", wd = { "Q1310967" }, label = "自動車修理工場" },
		car_sharing = { group = "go", wd = { "Q847201" }, label = "カーシェアリング" },
		charging_station = { group = "go", wd = { "Q2140665", "Q55956304" }, label = "充電ステーション" },
		cycle_track = { group = "go", wd = { "Q25037910", "Q221722" }, label = "自転車道" },
		ferry = { group = "go", wd = { "Q100355757", "Q25653", "Q1478783" }, label = "フェリー乗り場" },
		fuel = { group = "go", wd = { "Q205495" }, label = "ガソリンスタンド" },
		funicular = { group = "go", wd = { "Q142031" }, label = "ケーブルカー" },
		harbor = { alias = "port", group = "go", wd = { "Q44782", "Q283202" }, label = "港" },
		heliport = { group = "go", wd = { "Q502074" }, label = "ヘリポート" },
		landing_site = { group = "go", wd = { "Q3631092" }, label = "離着陸場" },
		left_luggage = { group = "go", wd = { "Q21996814" }, label = "手荷物置き場" },
		light_railway = { group = "go", wd = { "Q32680449" }, label = "軽便鉄道" },
		marina = { group = "go", wd = { "Q721207" }, label = "ヨットハーバー" },
		monorail = { group = "go", wd = { "Q187934" }, label = "モノレール駅" },
		motorbike_rental = { group = "go", label = "バイク貸出所" },
		motorway_junction = { group = "go", label = "高速道路のジャンクション" },
		parking = { group = "go", wd = { "Q6501349" }, label = "駐車場" },
		parking_garage = { group = "go", wd = { "Q13218805" }, label = "車庫" },
		pier = { group = "go", wd = { "Q863454" }, label = "桟橋" }, -- also jetty
		public_transport = { group = "go", wd = { "Q178512" }, label = "公共交通機関" },
		quay = { alias = "wharf", group = "go", wd = { "Q828909" }, label = "埠頭" },
		rail = { alias = { "train", "railway", "railway_station" }, group = "go", wd = { "Q55488", "Q55678" }, label = "鉄道駅" },
		scooter = { group = "go", wd = { "Q193234", "Q502057" }, label = "スクーター" },
		service_area = { group = "go", wd = { "Q786014" }, label = "サービスエリア" },
		ship = { group = "go", wd = { "Q11446" }, label = "大型船舶" },
		shipping_company = { group = "go", label = "船会社" },
		shuttle_bus_service = { group = "go", label = "シャトルバス" },
		station = { group = "go", wd = { "Q12819564" }, label = "駅" },
		subway = { alias = "metro", group = "go", wd = { "Q928830" }, label = "地下鉄", icon = "rail-metro" },
		taxi = { group = "go", wd = { "Q1395196" }, label = "タクシー" },
		terminal = { group = "go", wd = { "Q849706" }, label = "ターミナル" },
		toll_station = { group = "go", wd = { "Q1364150" }, label = "料金所" },
		tram = { group = "go", wd = { "Q2175765" }, label = "路面電車停留所", icon = "rail-light" },
		tunnel = { group = "go", wd = { "Q44377" }, label = "トンネル" },
		waiting_room = { group = "go", wd = { "Q674251" }, label = "待合室" },
		waypoint = { group = "go", wd = { "Q138081" }, label = "ウェイポイント" },
		-- group types
		go = { group = "go", wd = { "Q334166", "Q740752" }, label = "交通手段" },

		-- sights: religious sites and monuments

		altar = { group = "religion", wd = { "Q101687" }, label = "祭壇" },
		bahai_temple = { group = "religion", wd = { "Q1568313" }, label = "マシュリク・ル・アヅカル" },
		basilica = { group = "religion", wd = { "Q163687", "Q4846867" }, label = "バシリカ" },
		buddharupa = { group = "religion", wd = { "Q1000809" }, label = "仏像", icon = "religious-buddhist" },
		cathedral = { group = "religion", wd = { "Q2977" }, label = "大聖堂", icon = "religious-christian" },
		chapel = { group = "religion", wd = { "Q108325" }, label = "礼拝堂", icon = "religious-christian" },
		chapel_shrine = { group = "religion", wd = { "Q14552192" }, label = "礼拝の祠" },
		church = { group = "religion", wd = { "Q16970", "Q580499" }, label = "教会", icon = "religious-christian" },
		fire_temple = { group = "religion", wd = { "Q115278" }, label = "拝火神殿" },
		gurdwara = { group = "religion", wd = { "Q337986" }, label = "グルドワーラー" },
		hindu_temple = { group = "religion", wd = { "Q842402" }, label = "ヒンドゥー教寺院" },
		lak_mueang = { group = "religion", wd = { "Q974127" }, label = "ラックムアン" },
		minaret = { group = "religion", wd = { "Q48356" }, label = "ミナレット" },
		monastery = { group = "religion", wd = { "Q44613", "Q160742" }, label = "修道院" },
		mosque = { group = "religion", wd = { "Q32815" }, label = "モスク", icon = "religious-muslim" },
		nunnery = { group = "religion", wd = { "Q6021560" }, label = "女子僧院" },
		pagoda = { group = "religion", wd = { "Q199451" }, label = "仏塔" },
		pilgrimage_site = { group = "religion", wd = { "Q15135589" }, label = "巡礼地" },
		sanctuary = { group = "religion", wd = { "Q29553" }, label = "聖域" },
		shinto_shrine = { group = "religion", wd = { "Q845945" }, label = "神社", icon = "religious-shinto" },
		shrine = { group = "religion", wd = { "Q697295" }, label = "聖堂" },
		stupa = { group = "religion", wd = { "Q180987" }, label = "卒塔婆" },
		synagogue = { group = "religion", wd = { "Q34627" }, label = "シナゴーグ", icon = "religious-jewish" },
		temple = { group = "religion", wd = { "Q44539", "Q927825", "Q58621988" }, label = "寺院" },
		wat = { group = "religion", wd = { "Q427287" }, label = "ワット" },
		wayside_cross = { group = "religion", wd = { "Q2309609" }, label = "ウェイサイド・クロス" },
		wayside_shrine = { group = "religion", wd = { "Q3395121", "Q12661150" }, label = "祠" },
		religion = { alias = "religious_site", group = "religion", wd = { "Q1370598" }, label = "宗教施設" },

		-- sights: natural

		animal_stable = { group = "nature", wd = { "Q1207909" }, label = "畜舎" },
		aquarium = { group = "nature", wd = { "Q2281788" }, label = "水族館" },
		bay = { group = "nature", wd = { "Q39594", "Q17018380" }, label = "湾" },
		botanical_garden = { group = "nature", wd = { "Q167346" }, label = "植物園" },
		canal = { group = "nature", wd = { "Q12284" }, label = "運河" },
		canyon = { group = "nature", wd = { "Q150784" }, label = "峡谷" },
		cape = { group = "nature", wd = { "Q185113" }, label = "岬" },
		cave = { group = "nature", wd = { "Q35509" }, label = "洞窟" },
		cliff = { group = "nature", wd = { "Q107679" }, label = "崖" },
		coast = { group = "nature", wd = { "Q93352" }, label = "海岸" },
		crater = { group = "nature", wd = { "Q3240715" }, label = "クレーター" },
		crocodile_farm = { group = "nature", wd = { "Q25691" }, label = "ワニ農場" },
		depression = { group = "nature", wd = { "Q190429" }, label = "凹地" },
		desert = { group = "nature", wd = { "Q8514" }, label = "砂漠" },
		dog_park = { group = "nature", wd = { "Q38516" }, label = "ドッグラン" },
		dune = { group = "nature", wd = { "Q25391" }, label = "砂丘" },
		dyke = { group = "nature", wd = { "Q105190" }, label = "堤防" },
		farm = { group = "nature", wd = { "Q131596" }, label = "農場" },
		fish_pond = { group = "nature", wd = { "Q1265665" }, label = "養魚場" },
		fjord = { group = "nature", wd = { "Q45776" }, label = "フィヨルド" },
		forest = { group = "nature", wd = { "Q4421" }, label = "森" },
		garden = { group = "nature", wd = { "Q1107656" }, label = "庭" },
		geyser = { group = "nature", wd = { "Q83471" }, label = "間欠泉" },
		glacier = { group = "nature", wd = { "Q35666" }, label = "氷河" },
		gulf = { group = "nature", wd = { "Q1322134" }, label = "湾" },
		habitat = { group = "nature", label = "生息地" },
		hill = { group = "nature", wd = { "Q54050" }, label = "丘" },
		hot_spring = { group = "nature", wd = { "Q177380" }, label = "温泉" },
		island = { group = "nature", wd = { "Q23442" }, label = "島" },
		lagoon = { group = "nature", wd = { "Q187223" }, label = "ラグーン" },
		lake = { group = "nature", wd = { "Q23397" }, label = "湖" },
		landscape = { group = "nature", wd = { "Q107425" }, label = "景観" },
		mangrove = { group = "nature", wd = { "Q19756" }, label = "マングローブ" },
		mountain = { group = "nature", wd = { "Q8502" }, label = "山" },
		mountain_chain = { group = "nature", wd = { "Q2624046" }, label = "連山" },
		mountain_pass = { group = "nature", wd = { "Q133056" }, label = "峠" },
		mountain_range = { group = "nature", wd = { "Q46831" }, label = "山脈" },
		national_park = { group = "nature", wd = { "Q46169" }, label = "国立公園" },
		natural_heritage = { group = "nature", wd = { "Q386426" }, label = "自然遺産" },
		nature_reserve = { group = "nature", wd = { "Q158454", "Q179049", "Q473972", "Q20268756" }, label = "自然保護区" },
		oasis = { group = "nature", wd = { "Q43742" }, label = "オアシス" },
		palaeontological_site = { group = "nature", wd = { "Q9096832" }, label = "古生物学的遺跡" },
		park = { group = "nature", wd = { "Q22698", "Q728904" }, label = "公園" },
		peninsula = { group = "nature", wd = { "Q34763" }, label = "半島" },
		plantation = { group = "nature", wd = { "Q188913" }, label = "プランテーション" },
		plateau = { group = "nature", wd = { "Q75520" }, label = "高原" },
		protected_area = { alias = "protectorate", group = "nature", wd = { "Q473972" }, label = "保護地域" },
		reef = { group = "nature", wd = { "Q184358" }, label = "暗礁" },
		reservoir = { group = "nature", wd = { "Q131681" }, label = "貯水池" },
		river = { group = "nature", wd = { "Q4022" }, label = "川" },
		river_mouth = { group = "nature", wd = { "Q1233637" }, label = "河口" },
		rock = { group = "nature", wd = { "Q1404150" }, label = "岩石層" },
		sea = { group = "nature", wd = { "Q165" }, label = "海" },
		spring = { group = "nature", wd = { "Q124714" }, label = "泉" },
		steppe = { group = "nature", wd = { "Q123991" }, label = "ステップ地帯" },
		strait = { group = "nature", wd = { "Q37901" }, label = "海峡" },
		stream = { group = "nature", wd = { "Q47521" }, label = "小川" },
		stud = { group = "nature", wd = { "Q108696" }, label = "種馬飼育場" },
		summit = { group = "nature", wd = { "Q207326" }, label = "頂" },
		tree = { group = "nature", wd = { "Q10884" }, label = "木" },
		valley = { group = "nature", wd = { "Q39816" }, label = "谷" },
		volcano = { group = "nature", wd = { "Q8072" }, label = "火山" },
		waterfall = { group = "nature", wd = { "Q34038" }, label = "滝" },
		wetland = { group = "nature", wd = { "Q170321" }, label = "湿地" },
		zoo = { group = "nature", wd = { "Q43501" }, label = "動物園" },
		nature = { group = "nature", wd = { "Q7860" }, label = "自然環境" },

		-- sights: arts, historic

		amphitheater =  { group = "see", wd = { "Q54831" }, label = "円形劇場" },
		aqueduct = { group = "see", wd = { "Q474" }, label = "用水路" },
		archaeological_site = { group = "see", wd = { "Q839954" }, label = "遺跡" },
		architecture = { group = "see", wd = { "Q12271" }, label = "建築" },
		archive = { group = "see", wd = { "Q166118", "Q635719", "Q27032363" }, label = "アーカイブ" },
		artwork = { group = "see", wd = { "Q838948" }, label = "芸術作品" },
		barracks = { group = "see", wd = { "Q131263" }, label = "バラック" },
		boat_lift = { group = "see", wd = { "Q14908" }, label = "船舶昇降機" },
		bridge = { group = "see", wd = { "Q12280" }, label = "橋" },
		building = { group = "see", wd = { "Q41176", "Q811979" }, label = "建造物" },
		building_complex = { group = "see", wd = { "Q1497364", "Q18247357" }, label = "建築複合体" },
		bunker = { group = "see", wd = { "Q91122" }, label = "掩体壕" },
		cannon = { group = "see", wd = { "Q81103" }, label = "キャノン砲" },
		castle = { group = "see", wd = { "Q23413" }, label = "城" },
		cellar = { group = "see", wd = { "Q234852" }, label = "地下室" },
		cemetery = { group = "see", wd = { "Q39614" }, label = "墓地" },
		chateau = { alias = "château", group = "see", wd = { "Q751876" }, label = "シャトー" },
		city_center = { group = "see", wd = { "Q1468524" }, label = "副都心" },
		city_wall = { group = "see", wd = { "Q16748868" }, label = "市壁" },
		collection = { group = "see", wd = { "Q2668072", "Q7328910" }, label = "作品集" },
		column = { group = "see", wd = { "Q4817", "Q51845395", "Q1930585" }, label = "柱、塔" }, -- 248と違いを明確に
		communication_tower = { group = "see", wd = { "Q11166728", "Q1798641" }, label = "通信塔" },
		crematorium = { group = "see", wd = { "Q157570" }, label = "火葬場" },
		cultural_heritage = { group = "see", wd = { "Q210272" }, label = "文化遺産" },
		dam = { group = "see", wd = { "Q12323" }, label = "ダム" },
		embankment_dam = { group = "see", wd = { "Q1244922" }, label = "フィルダム" },
		exhibition = { group = "see", wd = { "Q464980" }, label = "展覧会" },
		factory = { group = "see", wd = { "Q83405" }, label = "工場" },
		fort = { group = "see", wd = { "Q57831" }, label = "要塞" },
		fountain = { group = "see", wd = { "Q483453" }, label = "噴水" },
		gallery = { group = "see", wd = { "Q1007870" }, label = "画廊", icon = "art-gallery" },
		gate = { group = "see", wd = { "Q53060" }, label = "門" },
		ghost_town = { group = "see", wd = { "Q74047" }, label = "廃村" },
		graduation_tower = { group = "see", wd = { "Q1541226" }, label = "グラディアヴェルク" },
		grave = { group = "see", wd = { "Q173387" }, label = "墓" },
		hall = { group = "see", wd = { "Q240854" }, label = "ホール" },
		handicraft = { group = "see", wd = { "Q52105" }, label = "生息地" },
		historic_district = { group = "see", wd = { "Q15243209" }, label = "歴史地区", icon = "historic" },
		house = { group = "see", wd = { "Q3947" }, label = "住宅" },
		hydraulic_structure = { group = "see", wd = { "Q2466889" }, label = "水利施設" },
		landmark = { group = "see", wd = { "Q2319498" }, label = "ランドマーク" },
		lighthouse = { group = "see", wd = { "Q39715" }, label = "燈台" },
		lock = { group = "see", wd = { "Q105731" }, label = "閘門" },
		mausoleum = { group = "see", wd = { "Q162875" }, label = "廟" },
		memorial = { group = "see", wd = { "Q5003624" }, label = "記念物" },
		mill = { group = "see", wd = { "Q44494" }, label = "粉砕機" },
		mine = { group = "see", wd = { "Q820477" }, label = "鉱山" }, -- including surface mining
		mining_museum = { group = "see", wd = { "Q819426" }, label = "鉱業博物館" },
		monument = { group = "see", wd = { "Q4989906" }, label = "モニュメント" },
		museum = { group = "see", wd = { "Q33506" }, label = "博物館、美術館" },
		museum_ship = { group = "see", wd = { "Q575727" }, label = "博物館船" },
		obelisk = { group = "see", wd = { "Q170980" }, label = "オベリスク" },
		observatory = { group = "see", wd = { "Q1254933", "Q62832" }, label = "天文台" },
		old_town = { group = "see", wd = { "Q676050" }, label = "旧市街", icon = "historic" },
		open_air_museum = { group = "see", wd = { "Q756102" }, label = "野外博物館" },
		palace = { group = "see", wd = { "Q16560" }, label = "宮殿" },
		pavilion = { alias = "arbor", group = "see", wd = { "Q276173", "Q23457088", "Q961082" }, label = "パビリオン、東屋" },
		pedestrian = { group = "see", wd = { "Q369730" }, label = "歩行者天国" },
		planetarium = { group = "see", wd = { "Q148319" }, label = "プラネタリウム" },
		power = { group = "see", wd = { "Q159719" }, label = "発電所" }, -- power station, transformers, towers etc.
		promenade = { group = "see", wd = { "Q787113" }, label = "遊歩道" },
		pyramid = { group = "see", wd = { "Q12516" }, label = "ピラミッド" },
		quarry = { group = "see", wd = { "Q15115254" }, label = "石切場" },
		road = { group = "see", wd = { "Q34442", "Q83620" }, label = "道" }, -- including street and lane
		rock_art = { group = "see", wd = { "Q1211146" }, label = "洞窟壁画" },
		ruins = { group = "see", wd = { "Q109607" }, label = "廃墟" },
		shipyard = { group = "see", wd = { "Q190928" }, label = "造船所" },
		spaceport = { group = "see", wd = { "Q194188" }, label = "発射場" },
		square = { group = "see", wd = { "Q174782" }, label = "広場" },
		statue = { group = "see", wd = { "Q179700" }, label = "塑像" },
		stele = { group = "see", wd = { "Q178743" }, label = "石碑" },
		stolperstein = { group = "see", wd = { "Q314003" }, label = "躓きの石" },
		technical_monument = { group = "see", wd = { "Q1516537" }, label = "技術的記念物" },
		tomb = { group = "see", wd = { "Q381885", "Q6023295" }, label = "墓" },
		tower = { group = "see", wd = { "Q12518" }, label = "塔" }, -- 194と違いを明確に
		town_hall = { group = "see", wd = { "Q543654" }, label = "市庁舎" },
		tumulus = { group = "see", wd = { "Q34023" }, label = "古墳" },
		viaduct =  { group = "see", wd = { "Q181348" }, label = "高架橋" },
		wall =  { group = "see", wd = { "Q42948" }, label = "壁" },
		war_grave = { group = "see", wd = { "Q90717531" }, label = "戦没者墓地" },
		watermill = { group = "see", wd = { "Q185187" }, label = "水車小屋" },
		weather_station = { group = "see", wd = { "Q190107" }, label = "気象台" },
		weir = { group = "see", wd = { "Q1066997" }, label = "堰" },
		well = { group = "see", wd = { "Q43483" }, label = "井戸" },
		windmill = { group = "see", wd = { "Q38720" }, label = "風車" },
		wreck = { group = "see", wd = { "Q852190" }, label = "難破船" },
		-- group types
		see = { group = "see", wd = { "Q570116" }, label = "観光名所" },

		-- culture

		arena = { group = "do", wd = { "Q641226" }, label = "アリーナ" },
		arts_center = { group = "do", wd = { "Q2190251" }, label = "芸術センター" },
		bird_watching = { group = "do", wd = { "Q685629" }, label = "バードウォッチング" },
		bullring = { group = "do", wd = { "Q1193438" }, label = "闘牛場" },
		cabaret = { group = "do", wd = { "Q131183" }, label = "キャバレー" },
		cinema = { group = "do", wd = { "Q41253" }, label = "映画館" },
		circus = { group = "do", wd = { "Q47928" }, label = "サーカス" },
		concert_hall = { group = "do", wd = { "Q1060829" }, label = "コンサートホール" },
		conference_center = { group = "do", wd = { "Q1378975" }, label = "展示場" },
		cultural_center = { group = "do", wd = { "Q1329623" }, label = "文化センター" },
		edutainment = { group = "do", wd = { "Q1153173" }, label = "エデュテインメント" },
		event = { group = "do", wd = { "Q1190554" }, label = "イベント" },
		event_venue = { group = "do", wd = { "Q18674739" }, label = "イベント会場" },
		fair = { group = "do", wd = { "Q57305", "Q2948561" }, label = "見本市" },
		festival = { group = "do", wd = { "Q132241" }, label = "祭" },
		heritage_railway = { group = "do", wd = { "Q420962" }, label = "保存鉄道" },
		karaoke = { group = "do", wd = { "Q229345" }, label = "カラオケ" },
		[ "multi-purpose_hall" ] = { group = "do", wd = { "Q1763828", "Q2400020" }, label = "多目的ホール" },
		music = { group = "do", wd = { "Q638" }, label = "音楽" }, -- different types of music theaters
		opera_house = { group = "do", wd = { "Q153562" }, label = "オペラハウス" },
		puppet_theater = { group = "do", wd = { "Q3982337" }, label = "人形劇場" },
		theater = { group = "do", wd = { "Q11635", "Q24354" }, label = "劇場", icon = "theatre" }, -- speech theater, theater in general
		themed_travel = { group = "do", label = "テーマ別旅行" },
		wildlife_observation = { group = "do", wd = { "Q28455557" }, label = "野生動物観察" },

		-- recreation

		amusement_park = { group = "do", wd = { "Q194195" }, label = "遊園地" },
		attraction = { group = "do", wd = { "Q2800000" }, label = "アトラクション" },
		ballooning = { group = "do", wd = { "Q805325" }, label = "熱気球競技" },
		casino = { group = "do", wd = { "Q133215" }, label = "カジノ" },
		dolphinarium = { group = "do", wd = { "Q491675" }, label = "イルカの水族館" },
		entertainment = { group = "do", wd = { "Q173799" }, label = "娯楽施設" },
		escape_game = { group = "do", wd = { "Q1201679" }, label = "脱出ゲーム" },
		horse_riding = { group = "do", wd = { "Q179226" }, label = "乗馬" },
		massage = { group = "do", wd = { "Q179415" }, label = "マッサージサロン" },
		playground = { group = "do", wd = { "Q11875349" }, label = "遊び場" },
		public_bath = { group = "do", wd = { "Q785952" }, label = "公衆浴場" },
		ropes_course = { group = "do", wd = { "Q1939700" }, label = "フィールドアスレチック" },
		sauna = { group = "do", wd = { "Q57036" }, label = "サウナ" },
		spa = { alias = "wellness", group = "do", wd = { "Q6882870" }, label = "スパ" },
		theme_park = { group = "do", wd = { "Q2416723" }, label = "テーマパーク" },
		water_park = { group = "do", wd = { "Q740326", "Q118559331" }, label = "ウォーターパーク" },
		youth_center = { group = "do", wd = { "Q1302299" }, label = "青少年クラブ" },

		-- sports and fitness

		["9pin"] = { group = "do", wd = { "Q706199" }, label = "Kegeln" },
		["10pin"] = { alias = "bowling", group = "do", wd = { "Q172809" }, label = "Bowling", icon = "bowling-alley" },
		athletics_track = { group = "do", wd = { "Q1004435", "Q37025296", "Q121072018" }, label = "Leichtathletikanlage" },
		badminton = { group = "do", wd = { "Q7291" }, label = "Badminton" },
		basketball_court = { group = "do", wd = { "Q2341939" }, label = "Basketballfeld" },
		beach = { group = "do", wd = { "Q40080" }, label = "Strand" },
		beachvolleyball = { group = "do", wd = { "Q4543" }, label = "Beachvolleyball" },
		bicycle_route = { group = "do", wd = { "Q353027", "Q102307360" }, label = "Radwanderweg" },
		billiards = { group = "do", wd = { "Q3341285" }, label = "Billiard" },
		bmx = { group = "do", wd = { "Q215184" }, label = "BMX" },
		boat_rental = { group = "do", wd = { "Q25384001" }, label = "Bootsverleih" },
		bobsleigh = { group = "do", wd = { "Q177275" }, label = "Bobsport" },
		bouldering = { group = "do", wd = { "Q852989" }, label = "Bouldern" },
		boules = { group = "do", wd = { "Q895060" }, label = "Boules" },
		bungee_jumping = { group = "do", wd = { "Q193847" }, label = "Bungeespringen" },
		canoe = { group = "do", wd = { "Q171529" }, label = "Bootssport" }, -- Kanu, Kayak
		canyoning = { group = "do", wd = { "Q206091" }, label = "Canyoning" },
		city_beach = { group = "do", wd = { "Q7900097" }, label = "Stadtstrand" }, -- incl. beach club
		climbing = { group = "do", wd = { "Q22857" }, label = "Bergsteigen" },
		court = { group = "do", wd = { "Q41487" }, label = "Gericht, Tribunal" },
		cricket = { group = "do", wd = { "Q5375" }, label = "Cricket" },
		cycling = { group = "do", wd = { "Q53121" }, label = "Radfahren" },
		dive_center = { group = "do", wd = { "Q3664857" }, label = "Tauchbasis" },
		downhill = { group = "do", wd = { "Q319899", "Q121071424" }, label = "Ski Alpin, Abfahrt", icon = "skiing" }, -- alpine/downhill ski route
		equestrian = { group = "do", wd = { "Q902378" }, label = "Reitsport" },
		extreme_sports = { group = "do", wd = { "Q309162" }, label = "Extremsport" },
		fishing = { group = "do", wd = { "Q14373" }, label = "Fischen, Angeln" },
		fitness_center = { alias = "gym", group = "do", wd = { "Q1065656", "Q30750411" }, label = "Fitnessstudio", icon = "fitness-centre" },
		football_pitch = { group = "do", wd = { "Q105755419" }, label = "Fußballfeld" },
		gliding = { group = "do", wd = { "Q624161" }, label = "Segelflug" },
		golf = { group = "do", wd = { "Q5377" }, label = "Golf (Sport)" },
		hiking = { alias = "trekking", group = "do", wd = { "Q12014035" }, label = "Wandern" },
		hillwalking = { group = "do", wd = { "Q1762646" }, label = "Bergwandern" },
		horse_racing = { group = "do", wd = { "Q187916" }, label = "Pferderennen" },
		hunting = { group = "do", wd = { "Q36963" }, label = "Jagd" },
		ice_hockey = { group = "do", wd = { "Q41466" }, label = "Eishockey" },
		ice_rink = { group = "do", wd = { "Q1282870" }, label = "Eisbahn" },
		ice_skating = { group = "do", wd = { "Q779272" }, label = "Eislaufen" },
		ice_stadium = { group = "do", wd = { "Q12019965" }, label = "Eissporthalle" },
		indoor_pool = { group = "do", wd = { "Q357380" }, label = "Hallenbad" },
		karting = { group = "do", wd = { "Q192420" }, label = "Kartsport" },
		kitesurfing = { group = "do", wd = { "Q219554" }, label = "Kitesurfen" },
		leisure_center = { group = "do", wd = { "Q30313989" }, label = "Freizeitzentrum" },
		mountain_biking = { group = "do", wd = { "Q520611", "Q223705" }, label = "Mountainbikesport" },
		minigolf = { group = "do", wd = { "Q754796" }, label = "Minigolf" },
		motocross = { group = "do", wd = { "Q215862" }, label = "Motocross" },
		nordic = { group = "do", wd = { "Q216613" }, label = "Ski Nordisch" }, -- nordic/cross country ski trail
		orienteering = { group = "do", wd = { "Q29358" }, label = "Orientierungslauf" },
		outdoor_pool = { group = "do", wd = { "Q13586493" }, label = "Freibad" },
		parachuting = { alias = "skydiving", group = "do", wd = { "Q193210" }, label = "Fallschirmspringen" },
		paragliding = { group = "do", wd = { "Q178380" }, label = "Paragliding" },
		polo = { group = "do", wd = { "Q134211" }, label = "Polo" },
		quad_bike = { group = "do", wd = { "Q3926537" }, label = "Quad-Bike" },
		racetrack = { group = "do", wd = { "Q1777138" }, label = "Rennbahn" },
		rafting = { group = "do", wd = { "Q207238" }, label = "Rafting" }, -- including whitewater rafting
		roller_skating = { group = "do", wd = { "Q1707432" }, label = "Rollsport" }, -- including inline roller skating
		rowing = { group = "do", wd = { "Q159354" }, label = "Rudern" },
		running = { group = "do", wd = { "Q3694569" }, label = "Laufsport" },
		sailing = { group = "do", wd = { "Q192520" }, label = "Segeln" },
		sandboarding = { group = "do", wd = { "Q570459" }, label = "Sandboarding" },
		scuba_diving = { group = "do", wd = { "Q1096878" }, label = "Tauchen" },
		shooting_range = { group = "do", wd = { "Q521839" }, label = "Schießstand, Schießplatz" },
		skatepark = { group = "do", wd = { "Q909906" }, label = "Skatepark" },
		ski_jumping = { group = "do", wd = { "Q7718" }, label = "Skispringen" },
		ski_school = { group = "do", wd = { "Q2292514" }, label = "Skischule" },
		skitour = { group = "do", wd = { "Q1075998" }, label = "Skitour" },
		sledding = { group = "do", wd = { "Q3266340" }, label = "Rodeln" },
		snorkeling = { group = "do", wd = { "Q2471422" }, label = "Schnorcheln" },
		snow_park = { group = "do", wd = { "Q3141488" }, label = "Snowpark" },
		soccer = { group = "do", wd = { "Q2736" }, label = "Fußball" },
		summer_toboggan = { group = "do", wd = { "Q3266345" }, label = "Sommerrodelbahn" },
		sports = { group = "do", wd = { "Q349" }, label = "Sport" },
		sports_venue = { group = "do", wd = { "Q1076486", "Q121071543", "Q120169931" }, label = "Sportstätte" },
		squash = { group = "do", wd = { "Q121072153", "Q121085278" }, label = "Squash" },
		stadium = { group = "do", wd = { "Q483110", "Q37025296" }, label = "Stadion" },
		surfing = { group = "do", wd = { "Q159992" }, label = "Surfen" },
		swimming = { group = "do", wd = { "Q6388" }, label = "Schwimmen" },
		swimming_pool = { group = "do", wd = { "Q200023" }, label = "Schwimmbad" },
		tennis = { alias = "tennis_court", group = "do", wd = { "Q847", "Q741118" }, label = "Tennisplatz" },
		toboggan = { group = "do", wd = { "Q56611604" }, label = "Rodelbahn" },
		tour = { group = "do", label = "Tour, Rundfahrt" },
		trail = { alias = "hiking_trail", wd = { "Q2143825" }, group = "do", label = "Wanderweg" },
		triathlon = { group = "do", wd = { "Q10980" }, label = "Triathlon" },
		velodrome = { group = "do", wd = { "Q830528" }, label = "Radrennbahn", icon = "racetrack-cycling" },
		wakeboarding = { group = "do", wd = { "Q376040" }, label = "Wakeboarding" },
		water_skiing = { group = "do", wd = { "Q472827" }, label = "Wasserski" },
		water_sports = { group = "do", wd = { "Q61065" }, label = "Wassersport" },
		winter_sports = { group = "do", wd = { "Q204686" }, label = "Wintersport" },
		-- group types
		["do"] = { group = "do", label = "Aktivität" },

		-- shopping

		alcohol_shop = { group = "buy", wd = { "Q2632011" }, label = "Spirituosengeschäft" },
		antiquarian = { group = "buy", wd = { "Q582794" }, label = "Antiquariat" },
		atm = { group = "buy", wd = { "Q81235" }, label = "Geldautomat, Bankomat" },
		bakery = { group = "buy", wd = { "Q274393" }, label = "Bäckerei" },
		bank = { group = "buy", wd = { "Q22687" }, label = "Bank, Geldwesen" },
		beverages = { group = "buy", wd = { "Q47504516" }, label = "Getränkegeschäft" },
		bike_shop = { group = "buy", wd = { "Q26721034" }, label = "Fahrradladen" },
		book_seller = { alias = "book_shop", group = "buy", wd = { "Q200764" }, label = "Buchhandlung" },
		boutique = { group = "buy", wd = { "Q1068824" }, label = "Boutique" },
		business_park = { group = "buy", wd = { "Q338313" }, label = "Gewerbegebiet" },
		butchery = { group = "buy", wd = { "Q13164546" }, label = "Metzgerei, Fleischerei" },
		carpet_shop = { group = "buy", wd = { "Q47516346" }, label = "Teppichgeschäft" },
		cheesery = { group = "buy", wd = { "Q3088348" }, label = "Käserei" },
		chemist = { alias = "drugstore", group = "buy", wd = { "Q1260046" }, label = "Drogerie" },
		collector_shop = { group = "buy", label = "Sammlergeschäft" },
		cosmetics_shop = { group = "buy", wd = { "Q47508166" }, label = "Kosmetik" },
		crafts_shop = { group = "buy", wd = { "Q101061294" }, label = "Handwerksgeschäft" },
		currency_exchange = { group = "buy", wd = { "Q2002539" }, label = "Wechselstube" },
		delicatessen = { group = "buy", wd = { "Q3231410" }, label = "Feinkostladen" },
		department_store = { group = "buy", wd = { "Q216107" }, label = "Warenhaus, Kaufhaus" },
		["duty-free_shop"] = { group = "buy", wd = { "Q545609" }, label = "Duty-Free-Geschäft" },
		fashion_store = { alias = "clothing_store", group = "buy", wd = { "Q2090555" }, label = "Modeladen, Bekleidungsgeschäft", icon = "clothing-store" },
		farm_shop = { group = "buy", wd = { "Q1371823" }, label = "Hofladen" },
		flea_market = { group = "buy", wd = { "Q385870" }, label = "Flohmarkt" },
		florist = { group = "buy", wd = { "Q10431511" }, label = "Blumenladen" },
		grocery = { group = "buy", wd = { "Q1295201" }, label = "Lebensmittelladen" },
		hairdresser = { group = "buy", wd = { "Q95856773" }, label = "Friseur" },
		industrial_park = { group = "buy", wd = { "Q1662100" }, label = "Industriepark" },
		jewellery = { group = "buy", wd = { "Q20708021" }, label = "Juwelier", icon = "jewelry-store" },
		kiosk = { group = "buy", wd = { "Q693369" }, label = "Kiosk" },
		mall = { group = "buy", wd = { "Q11315", "Q31374404" }, label = "Einkaufszentrum, Mall" },
		market = { group = "buy", wd = { "Q37654" }, label = "Markt" },
		music_shop = { group = "buy", wd = { "Q24284215" }, label = "Musikgeschäft" },
		optician = { group = "buy", wd = { "Q80144507" }, label = "Optiker" },
		outdoor_retailer = { group = "buy", label = "Outdoor-Händler" },
		outlet = { group = "buy", wd = { "Q76470" }, label = "Outlet, Fabrikverkauf" },
		pastry_shop = { alias = "confectionery", group = "buy", wd = { "Q47505416" }, label = "Konditorei, Feinbäckerei" },
		photo_store = { group = "buy", wd = { "Q57262241" }, label = "Fotogeschäft" },
		second_hand = { group = "buy", wd = { "Q2925872" }, label = "Gebrauchtwarenladen" },
		shoe_shop = { group = "buy", wd = { "Q7500021" }, label = "Schuhladen", icon = "shoe" },
		shop = { group = "buy", wd = { "Q213441" }, label = "Geschäft, Laden, Shop" },
		shopping_district = { group = "buy", wd = { "Q27095213" }, label = "Einkaufsviertel" },
		shopping_street = { group = "buy", wd = { "Q21000333" }, label = "Einkaufsstraße" },
		souvenir_shop = { group = "buy", wd = { "Q865693" }, label = "Souvenirgeschäft, Andenkenladen" },
		sports_shop = { group = "buy", wd = { "Q47516567" }, label = "Sportgeschäft" },
		supermarket = { group = "buy", wd = { "Q180846" }, label = "Supermarkt" },
		ticket_shop = { alias = "box_office", group = "buy", wd = { "Q47519615", "Q877435" }, label = "Ticketverkauf" },
		vending_machine = { group = "buy", wd = { "Q211584" }, label = "Verkaufsautomat" },
		watersports_shop = { group = "buy", label = "Wassersportgeschäft" },
		-- group types
		buy = { group = "buy", label = "Einkaufen" },

		-- cuisine, eating

		agriculture = { group = "eat", wd = { "Q11451" }, label = "Landwirtschaft" },
		bistro = { group = "eat", wd = { "Q866742" }, label = "Bistro" },
		brasserie = { group = "eat", wd = { "Q1581509" }, label = "Brasserie" },
		cafe = { group = "eat", wd = { "Q30022" }, label = "Café, Kaffeehaus" },
		cafeteria = { group = "eat", wd = { "Q8463304" }, label = "Cafeteria" },
		canteen = { group = "eat", wd = { "Q54957790" }, label = "Kantine" }, -- auch für Mensa
		community_kitchen = { group = "eat", wd = { "Q28854744" }, label = "Gemeinschaftsküche, Langar" },
		fast_food = { group = "eat", wd = { "Q1751429" }, label = "Fastfood, Schnellrestaurant" },
		food = { group = "eat", wd = { "Q2095", "Q736427" }, label = "Lebensmittel" },
		ice_cream = { group = "eat", wd = { "Q1311064" }, label = "Eisdiele" },
		izakaya = { group = "eat", wd = { "Q1193068" }, label = "Izakaya-Restaurant" },
		picnic = { group = "eat", wd = { "Q506294" }, label = "Picknick", icon = "picnic-site" },
		pizzeria = { group = "eat", wd = { "Q1501212" }, label = "Pizzeria", icon = "restaurant-pizza" },
		restaurant = { group = "eat", wd = { "Q11707" }, label = "Restaurant, Gaststätte, Lokal" },
		seafood_restaurant = { alias = "seafood", group = "eat", wd = { "Q17102985" }, label = "Seefisch-Restaurant", icon = "restaurant-seafood" },
		snack_bar = { group = "eat", wd = { "Q1318768" }, label = "Food-counter, Imbissstand" },
		steak_house = { group = "eat", wd = { "Q3109696" }, label = "Steakhaus" },
		street_food = { group = "eat", wd = { "Q1316209" }, label = "Street Food" },
		takeaway = { group = "eat", wd = { "Q154383", "Q506946" }, label = "Take-away, Imbissstand, Würstelstand" },
		tavern = { group = "eat", wd = { "Q154250", "Q2387565" }, label = "Taverne" },
		teahouse = { group = "eat", wd = { "Q1072166" }, label = "Teehaus" },
		-- group types
		eat = { group = "eat", wd = { "Q27038993", "Q27077054" }, label = "Küche, Essen" },

		-- drinking, going out

		bar = { group = "drink", wd = { "Q187456" }, label = "Bar" },
		beer_garden = { group = "drink", wd = { "Q857909" }, label = "Biergarten", icon = "beer" },
		brewery = { group = "drink", wd = { "Q131734" }, label = "Brauerei" },
		club = { group = "drink", label = "Club" },
		discotheque = { group = "drink", wd = { "Q1228895" }, label = "Diskothek" },
		distillery = { group = "drink", wd = { "Q1251750" }, label = "Brennerei" },
		drinking_hall = { group = "drink", wd = { "Q4101440" }, label = "Trinkhalle" },
		drinking_water = { group = "drink", wd = { "Q7892" }, label = "Trinkwasser" },
		nightclub = { group = "drink", wd = { "Q622425" }, label = "Nachtclub" },
		pub = { group = "drink", wd = { "Q19754932", "Q12341378" }, label = "Kneipe" },
		vineyard = { group = "drink", wd = { "Q22715" }, label = "Weingut, Weinberg" },
		winery = { group = "drink", wd = { "Q20181766" }, label = "Kellerei" },
		-- group types
		drink = { group = "drink", wd = { "Q5307737" }, label = "Trinken" },

		-- accommodation

		appartment = { group = "sleep", wd = { "Q617839" }, label = "Appartement-Hotel" },
		alpine_hut = { group = "sleep", wd = { "Q182676" }, label = "Berghütte" },
		bed_and_bike = { group = "sleep", label = "Bett und Bike" },
		bnb = { group = "sleep", subtype = "y", wd = { "Q367914" }, label = "Bed & Breakfast", icon = "lodging" },
		boarding_house = { group = "sleep", subtype = "y", wd = { "Q1558858", "Q1065252" }, label = "Pension" },
		campsite = { group = "sleep", wd = { "Q832778" }, label = "Campingplatz, Zeltplatz" },
		caravan_site = { group = "sleep", label = "Caravan-Campingplatz" },
		chalet = { group = "sleep", label = "Chalet, Ferienhaus" },
		ecolodge = { group = "sleep", wd = { "Q3577646" }, label = "Ecolodge" },
		group_accomodation = { group = "sleep", label = "Gruppenunterkunft" },
		guest_house = { group = "sleep", wd = { "Q2460422" }, label = "Gästehaus" },
		holiday_flat = { group = "sleep", wd = { "Q336532" }, label = "Ferienwohnung" },
		hostel = { group = "sleep", wd = { "Q654772" }, label = "Herberge, Hostel", icon = "lodging" },
		hotel = { group = "sleep", wd = { "Q27686", "Q63099748" }, label = "Hotel", icon = "lodging" },
		hotel_garni = { group = "sleep", subtype = "y", wd = { "Q1631103" }, label = "Hotel garni", icon = "lodging" },
		motel = { group = "sleep", wd = { "Q216212" }, label = "Motel", icon = "lodging" },
		resort = { group = "sleep", wd = { "Q875157" }, label = "Resort" },
		wilderness_hut = { group = "sleep", wd = { "Q17087359" }, label = "Wildnishütte" },
		youth_hostel = { group = "sleep", wd = { "Q1589077" }, label = "Jugendherberge" },
		-- group types
		sleep = { group = "sleep", wd = { "Q5056668" }, label = "Unterkunft" },

		-- people

		children = { group = "other", wd = { "Q7569" }, label = "Kinder" },

		-- health

		clinic = { group = "health", wd = { "Q1774898" }, label = "Klinik" },
		defibrillator = { group = "health", wd = { "Q1450682" }, label = "Defibrillator" },
		dental_emergency_service = { group = "health", label = "Zahnärztlicher Notdienst" },
		dentist = { group = "health", wd = { "Q2979300" }, label = "Zahnarzt" },
		doctor = { alias ="surgery", group = "health", wd = { "Q718966" }, label = "Arztpraxis" },
		emergency_medical_services = { group = "health", wd = { "Q860447" }, label = "Rettungsdienst, Notfallrettung" },
		first_aid = { group = "health", wd = { "Q133981" }, label = "Erste Hilfe" },
		health = { group = "health", wd = { "Q12147" }, label = "Gesundheit" },
		health_center = { group = "health", wd = { "Q569500" }, label = "Ärztehaus" },
		hospital = { group = "health", wd = { "Q16917" }, label = "Krankenhaus" },
		laboratory = { group = "health", wd = { "Q483242", "Q112203425" }, label = "Labor" },
		["medical_on-call_service"] = { group = "health", label = "Ärztlicher Bereitschaftsdienst" },
		naturopathy = { group = "health", wd = { "Q213403" }, label = "Naturheilkunde" },
		nursing_home = { group = "health", wd = { "Q837142" }, label = "Pflegeheim" },
		pharmacy = { group = "health", wd = { "Q13107184" }, label = "Apotheke" },
		pharmacy_on_standby_duty = { group = "health", label = "Apotheken-Notdienst" },
		rehabilitation = { group = "health", wd = { "Q2795791" }, label = "Rehabilitation, Kurklinik" },
		rescue_center = { group = "health", label = "Rettungsstation" },
		veterinary = { group = "health", wd = { "Q15850915" }, label = "Tierarzt" },

		-- teaching & learning

		academy = { group = "other", wd = { "Q162633" }, label = "Akademie" },
		bookcase = { group = "other", wd = { "Q215857" }, label = "Bücherschrank" },
		college = { group = "other", wd = { "Q189004" }, label = "Hochschule, College" },
		cooking_class = { group = "other", label = "Kochkurs" },
		education = { alias = "learn", group = "other", wd = { "Q8434" }, label = "Ausbildung" },
		folk_high_school = { group = "other", wd = { "Q170087" }, label = "Volkshochschule" },
		gymnasium = { group = "other", wd = { "Q55043" }, label = "Gymnasium" },
		institute = { group = "other", wd = { "Q1664720" }, label = "Institut" },
		kindergarten = { group = "other", wd = { "Q126807" }, label = "Kindergarten" },
		language_school = { group = "other", wd = { "Q897403" }, label = "Sprachschule" },
		library = { group = "other", wd = { "Q7075" }, label = "Bücherei" },
		nursery = { group = "other", wd = { "Q20174673" }, label = "Kinderkrippe" },
		school = { group = "other", wd = { "Q3914" }, label = "Schule" },
		university = { group = "other", wd = { "Q3918" }, label = "Universität" },

		-- administration and uncategorized

		administration = { group = "other", wd = { "Q5283295" }, label = "Verwaltung" },
		business_development_agency = { group = "other", label = "Wirtschaftsförderungsgesellschaft" },
		checkpoint = { group = "other", wd = { "Q88871664" }, label = "Kontrollpunkt" },
		company = { group = "other", wd = { "Q6881511" }, label = "Unternehmen" },
		consulate = { group = "other", wd = { "Q7843791" }, label = "Konsulat" },
		coworking_space = { group = "other", wd = { "Q97307779" }, label = "Coworking Space" },
		customs = { group = "other", wd = { "Q182290" }, label = "Zoll" },
		cultural_organisation = { group = "other", wd = { "Q29918292" }, label = "Kulturorganisation" },
		embassy = { group = "other", wd = { "Q3917681" }, label = "Botschaft" },
		emergency_call = { group = "other", wd = { "Q694554" }, label = "Notruf", icon = "emergency-phone" },
		fire_brigade = { group = "other", wd = { "Q6498663" }, label = "Feuerwehr", icon = "fire-station" },
		government = { group = "other", wd = { "Q16831714" }, label = "Regierungsgebäude" },
		guide = { group = "other", wd = { "Q14290559" }, label = "Fremdenführer" },
		hotline = { group = "other", wd = { "Q1482145" }, label = "Hotline" },
		internet_cafe = { group = "other", wd = { "Q272399" }, label = "Internetcafé" },
		laundry = { group = "other", wd = { "Q12893467" }, label = "Wäscherei" },
		list = { group = "other", wd = { "Q12139612", "Q13406463" }, label = "Liste" },
		lost_and_found = { group = "other", wd = { "Q15983979" }, label = "Fundbüro" },
		military = { group = "other", wd = { "Q8473" }, label = "Militär" },
		mobile_telephony = { group = "other", wd = { "Q47516435" }, label = "Mobilfunkgeschäft" },
		newspaper = { group = "other", wd = { "Q11032" }, label = "Zeitung, Zeitungsverlag" },
		office = { group = "other", wd = { "Q182060" }, label = "Büro" },
		organisation = { group = "other", wd = { "Q43229" }, label = "Organisation" },
		passport_office = { group = "other", label = "Passstelle" },
		phone = { group = "other", wd = { "Q11035" }, label = "Telefon", icon = "telephone" },
		police = { group = "other", wd = { "Q35535" }, label = "Polizei" },
		post = { group = "other", wd = { "Q35054" }, label = "Postamt" },
		register_office = { alias = { "standesamt", "registry_office" }, group = "other", wd = { "Q745221", "Q29127138", "Q206946" }, label = "Standesamt" },
		relief_organisation = { group = "other", wd = { "Q708676" }, label = "Wohltätigkeitsorganisation" },
		roadside_assistance = { group = "other", wd = { "Q337810" }, label = "Pannenhilfe, Unfallhilfe" },
		shelter = { group = "other", wd = { "Q7493941" }, label = "Unterstand" },
		toilet = { group = "other", wd = { "Q7857" }, label = "Toiletten" },
		tour_operator = { group = "other", wd = { "Q133744" }, label = "Reiseveranstalter" },
		tourism_authority = { group = "other", label = "Tourismusbehörde" },
		tourist_information = { alias = "visitor_center", group = "other", wd = { "Q1587716", "Q18411786" }, label = "Touristinformation, Fremdenverkehrsamt", icon = "information" },
		travel_agency = { group = "other", wd = { "Q217107" }, label = "Reisebüro" },
		weblink = { group = "other", wd = { "Q102014" }, label = "Weblink" },
		wlan = { group = "other", wd = { "Q334765" }, label = "WLAN-Hotspot" },
		work = { group = "other", wd = { "Q6958747" }, label = "Arbeit" },
		-- group types
		other = { group = "other", label = "Anderes" },
		listing = { group = "other", label = "Listung" },

		-- populated areas
		
		city = { group = "populated", wd = { "Q515" }, label = "Stadt" },
		fraction = { group = "populated", label = "Ortsteil einer Gemeinde" },
		holiday_resort = { group = "populated", wd = { "Q3077815" }, label = "Feriensiedlung" },
		municipality = { group = "populated", wd = { "Q15284", "Q17376095", "Q562061" }, label = "Gemeinde" },
		quarter = { alias = "neighborhood", group = "populated", wd = { "Q2983893", "Q253019" }, label = "Stadtteil" },
		refugee_camp = { group = "populated", wd = { "Q622499" }, label = "Flüchtlingscamp" },
		settlement = { group = "populated", wd = { "Q486972" }, label = "Siedlung" },
		town = { group = "populated", wd = { "Q3957" }, label = "Kleinstadt" },
		village = { group = "populated", wd = { "Q532" }, label = "Dorf" },

		-- views
		
		observation_tower = { group = "view", wd = { "Q1440300" }, label = "Aussichtsturm" },
		scenic_view = { group = "view", label = "Bildmotiv", icon = "attraction" },
		viewpoint = { group = "view", wd = { "Q6017969" }, label = "Aussichtspunkt" },

		-- areas

		adm1st = { group = "area", wd = { "Q10864048" }, label = "Verwaltungseinheit 1. Ebene" },
		adm2nd = { group = "area", wd = { "Q13220204" }, label = "Verwaltungseinheit 2. Ebene" },
		adm3rd = { group = "area", wd = { "Q13221722" }, label = "Verwaltungseinheit 3. Ebene" },
		country = { group = "area", wd = { "Q6256" }, label = "Land, Staat" },
		district = { group = "area", wd = { "Q149621" }, label = "Distrikt" },
		region = { group = "area", wd = { "Q82794" }, label = "Region" },
		surroundings = { group = "area", wd = { "Q2920644" }, label = "Umgebung" },
		vicinity = { group = "area", wd = { "Q16968816" }, label = "Nähe, nahe Umgebung" },

		-- error
		
		error = { group = "error", wd = { "Q29485" }, label = "エラー" }
	}
}